import type { Category } from "../schema"

export const categoriesArr: Category[] = [
  {
    code: 1,
    en: "Furniture",
    ro: "Mobilă",
    ru: "Мебель",
    layer: 1,
  },
  {
    code: 2,
    en: "Clothes",
    ro: "Haine",
    ru: "Одежда",
    layer: 1,
  },
  {
    code: 3,
    en: "Shoes",
    ro: "Incălțăminte",
    ru: "Обувь",
    layer: 1,
  },
  {
    code: 4,
    en: "Stationery",
    ro: "Papetărie",
    ru: "Канцелярские товары",
    layer: 1,
  },
  {
    code: 5,
    en: "Books",
    ro: "Cărți",
    ru: "Книги",
    layer: 1,
  },
  {
    code: 101,
    en: "Soft furniture",
    ro: "Mobilier textil",
    ru: "Мягкая мебель",
    layer: 2,
  },
  {
    code: 102,
    en: "Tables and chairs",
    ro: "Mese și scaune",
    ru: "Столы и стулья",
    layer: 2,
  },
  {
    code: 103,
    en: "Office furniture",
    ro: "Mobilier de birou",
    ru: "Офисная мебель",
    layer: 2,
  },
  {
    code: 104,
    en: "Storage furniture",
    ro: "Mobilier de depozitare",
    ru: "Мебель для хранения",
    layer: 2,
  },
  {
    code: 105,
    en: "Accessories",
    ro: "Accesorii",
    ru: "Комплектующие",
    layer: 2,
  },
  {
    code: 201,
    en: "For men",
    ro: "A bărbaţilor",
    ru: "Мужская",
    layer: 2,
  },
  {
    code: 202,
    en: "For women",
    ro: "Femei",
    ru: "Женская",
    layer: 2,
  },
  {
    code: 203,
    en: "For children",
    ro: "Pentru copii",
    ru: "Детская",
    layer: 2,
  },
  {
    code: 204,
    en: "Unisex",
    ro: "Unisex",
    ru: "Унисекс",
    layer: 2,
  },
  {
    code: 301,
    en: "For men",
    ro: "A bărbaţilor",
    ru: "Мужская",
    layer: 2,
  },
  {
    code: 302,
    en: "For women",
    ro: "Femei",
    ru: "Женская",
    layer: 2,
  },
  {
    code: 303,
    en: "For children",
    ro: "Pentru copii",
    ru: "Детская",
    layer: 2,
  },
  {
    code: 304,
    en: "Unisex",
    ro: "Unisex",
    ru: "Унисекс",
    layer: 2,
  },
  {
    code: 401,
    en: "Writing supplies",
    ro: "Articole de papetărie",
    ru: "Письменные принадлежности",
    layer: 2,
  },
  {
    code: 402,
    en: "Paper products",
    ro: "Produse de hârtie",
    ru: "Бумажная продукция",
    layer: 2,
  },
  {
    code: 403,
    en: "Paper",
    ro: "Hârtie",
    ru: "Бумага",
    layer: 2,
  },
  {
    code: 404,
    en: "Folders and files",
    ro: "Dosare și fișiere",
    ru: "Папки и файлы",
    layer: 2,
  },
  {
    code: 405,
    en: "Office supplies",
    ro: "Articole de birou",
    ru: "Офисные принадлежности",
    layer: 2,
  },
  {
    code: 501,
    en: "Fiction",
    ro: "Literatură artistică",
    ru: "Художественная литература",
    layer: 2,
  },
  {
    code: 502,
    en: "Comics",
    ro: "Benzi desenate",
    ru: "Комиксы",
    layer: 2,
  },
  {
    code: 503,
    en: "Manga",
    ro: "Manga",
    ru: "Манга",
    layer: 2,
  },
  {
    code: 504,
    en: "Educational literature",
    ro: "Literatură didactică",
    ru: "Учебная литература",
    layer: 2,
  },
  {
    code: 10101,
    en: "Sofas",
    ro: "Canapele",
    ru: "Диваны",
    layer: 3,
  },
  {
    code: 10102,
    en: "Armchairs",
    ro: "Fotolii",
    ru: "Кресла",
    layer: 3,
  },
  {
    code: 10103,
    en: "Accessories",
    ro: "Accesorii",
    ru: "Комплектующие",
    layer: 3,
  },
  {
    code: 10201,
    en: "Chairs",
    ro: "Scaune",
    ru: "Стулья",
    layer: 3,
  },
  {
    code: 10202,
    en: "Tables",
    ro: "Mese",
    ru: "Столы",
    layer: 3,
  },
  {
    code: 10203,
    en: "Stools",
    ro: "Scăunele",
    ru: "Табуреты",
    layer: 3,
  },
  {
    code: 10301,
    en: "Armchairs",
    ro: "Fotolii",
    ru: "Кресла",
    layer: 3,
  },
  {
    code: 10302,
    en: "Tables",
    ro: "Mese",
    ru: "Столы",
    layer: 3,
  },
  {
    code: 10303,
    en: "Chairs",
    ro: "Scaune",
    ru: "Стулья",
    layer: 3,
  },
  {
    code: 10401,
    en: "Cabinets",
    ro: "Dulapuri",
    ru: "Шкафы",
    layer: 3,
  },
  {
    code: 10402,
    en: "Drawers",
    ro: "Comode",
    ru: "Комоды",
    layer: 3,
  },
  {
    code: 10403,
    en: "Nightstands",
    ro: "Noptiere",
    ru: "Тумбы",
    layer: 3,
  },
  {
    code: 10501,
    en: "Hangers",
    ro: "Aragazuri",
    ru: "Вешалки",
    layer: 3,
  },
  {
    code: 10502,
    en: "Shoe racks",
    ro: "Rafturi pentru pantofi",
    ru: "Полки для обуви",
    layer: 3,
  },
  {
    code: 20101,
    en: "Shirts",
    ro: "Cămăși",
    ru: "Рубашки",
    layer: 3,
  },
  {
    code: 20102,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    code: 20103,
    en: "Pants",
    ro: "Pantaloni",
    ru: "Штаны",
    layer: 3,
  },
  {
    code: 20104,
    en: "Socks",
    ro: "Șosete",
    ru: "Носки",
    layer: 3,
  },
  {
    code: 20201,
    en: "Blouses",
    ro: "Bluze",
    ru: "Блузки",
    layer: 3,
  },
  {
    code: 20202,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    code: 20203,
    en: "Skirts",
    ro: "Fuste",
    ru: "Юбки",
    layer: 3,
  },
  {
    code: 20204,
    en: "Tights",
    ro: "Colanți",
    ru: "Колготы",
    layer: 3,
  },
  {
    code: 20301,
    en: "Shirts",
    ro: "Cămăși",
    ru: "Рубашки",
    layer: 3,
  },
  {
    code: 20302,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    code: 20303,
    en: "Pants",
    ro: "Pantaloni",
    ru: "Штаны",
    layer: 3,
  },
  {
    code: 20304,
    en: "Socks",
    ro: "Șosete",
    ru: "Носки",
    layer: 3,
  },
  {
    code: 20305,
    en: "Tights",
    ro: "Colanți",
    ru: "Колготы",
    layer: 3,
  },
  {
    code: 20401,
    en: "Shirts",
    ro: "Cămăși",
    ru: "Рубашки",
    layer: 3,
  },
  {
    code: 20402,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    code: 20403,
    en: "Pants",
    ro: "Pantaloni",
    ru: "Штаны",
    layer: 3,
  },
  {
    code: 20404,
    en: "Socks",
    ro: "Șosete",
    ru: "Носки",
    layer: 3,
  },
  {
    code: 30101,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    code: 30102,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    code: 30103,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    code: 30201,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    code: 30202,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    code: 30203,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    code: 30301,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    code: 30302,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    code: 30303,
    en: "Sneakers",
    ro: "Sneakers",
    ru: "Кроссовки",
    layer: 3,
  },
  {
    code: 30304,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    code: 30401,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    code: 30402,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    code: 30403,
    en: "Sneakers",
    ro: "Sneakers",
    ru: "Кроссовки",
    layer: 3,
  },
  {
    code: 30404,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    code: 40101,
    en: "Pens",
    ro: "Pixuri",
    ru: "Ручки",
    layer: 3,
  },
  {
    code: 40102,
    en: "Pencils",
    ro: "Creioane",
    ru: "Карандаши",
    layer: 3,
  },
  {
    code: 40103,
    en: "Felt-tip pens",
    ro: "Creioane colorate",
    ru: "Фломастеры",
    layer: 3,
  },
  {
    code: 40104,
    en: "Markers",
    ro: "Markere",
    ru: "Маркеры",
    layer: 3,
  },
  {
    code: 40201,
    en: "Notebooks",
    ro: "Caiete",
    ru: "Тетради",
    layer: 3,
  },
  {
    code: 40202,
    en: "Notepads",
    ro: "Blocnotes",
    ru: "Блокноты",
    layer: 3,
  },
  {
    code: 40203,
    en: "Planners",
    ro: "Planificatoare",
    ru: "Ежедневники",
    layer: 3,
  },
  {
    code: 40301,
    en: "Printer paper",
    ro: "Hârtie de imprimantă",
    ru: "Бумага для печати",
    layer: 3,
  },
  {
    code: 40302,
    en: "Colored paper",
    ro: "Hârtie colorată",
    ru: "Цветная бумага",
    layer: 3,
  },
  {
    code: 40303,
    en: "Drawing paper",
    ro: "Hârtie de desen",
    ru: "Бумага для черчения",
    layer: 3,
  },
  {
    code: 40401,
    en: "Folders",
    ro: "Dosare",
    ru: "Папки",
    layer: 3,
  },
  {
    code: 40402,
    en: "Files",
    ro: "Fișiere",
    ru: "Файлы",
    layer: 3,
  },
  {
    code: 40501,
    en: "Staplers",
    ro: "Capsator",
    ru: "Степлеры",
    layer: 3,
  },
  {
    code: 40502,
    en: "Paper punches",
    ro: "Perforatoare",
    ru: "Дыроколы",
    layer: 3,
  },
  {
    code: 40503,
    en: "Erasers",
    ro: "Gumă de șters",
    ru: "Ластики",
    layer: 3,
  },
  {
    code: 40504,
    en: "Correction fluid",
    ro: "Corectoare",
    ru: "Корректоры",
    layer: 3,
  },
  {
    code: 50101,
    en: "Sci-fi",
    ro: "SF",
    ru: "Научная фантастика",
    layer: 3,
  },
  {
    code: 50102,
    en: "Fantasy",
    ro: "Fantezie",
    ru: "Фэнтези",
    layer: 3,
  },
  {
    code: 50103,
    en: "Adventure",
    ro: "Aventură",
    ru: "Приключение",
    layer: 3,
  },
  {
    code: 50104,
    en: "Detective",
    ro: "Detectiv",
    ru: "Детектив",
    layer: 3,
  },
  {
    code: 50105,
    en: "Thriller",
    ro: "Thriller",
    ru: "Триллер",
    layer: 3,
  },
  {
    code: 50201,
    en: "Sci-fi",
    ro: "SF",
    ru: "Научная фантастика",
    layer: 3,
  },
  {
    code: 50202,
    en: "Fantasy",
    ro: "Fantezie",
    ru: "Фэнтези",
    layer: 3,
  },
  {
    code: 50203,
    en: "Adventure",
    ro: "Aventură",
    ru: "Приключение",
    layer: 3,
  },
  {
    code: 50204,
    en: "Detective",
    ro: "Detectiv",
    ru: "Детектив",
    layer: 3,
  },
  {
    code: 50205,
    en: "Thriller",
    ro: "Thriller",
    ru: "Триллер",
    layer: 3,
  },
  {
    code: 50301,
    en: "Sci-fi",
    ro: "SF",
    ru: "Научная фантастика",
    layer: 3,
  },
  {
    code: 50302,
    en: "Fantasy",
    ro: "Fantezie",
    ru: "Фэнтези",
    layer: 3,
  },
  {
    code: 50303,
    en: "Adventure",
    ro: "Aventură",
    ru: "Приключение",
    layer: 3,
  },
  {
    code: 50304,
    en: "Detective",
    ro: "Detectiv",
    ru: "Детектив",
    layer: 3,
  },
  {
    code: 50305,
    en: "Thriller",
    ro: "Thriller",
    ru: "Триллер",
    layer: 3,
  },
  {
    code: 50401,
    en: "Science",
    ro: "Ştiinţă",
    ru: "Наука",
    layer: 3,
  },
  {
    code: 50402,
    en: "Psychology",
    ro: "Psihologie",
    ru: "Психология",
    layer: 3,
  },
  {
    code: 50403,
    en: "History",
    ro: "Istorie",
    ru: "История",
    layer: 3,
  },
  {
    code: 50404,
    en: "Sociology",
    ro: "Sociologie",
    ru: "Социология",
    layer: 3,
  },
  {
    code: 50405,
    en: "Medicine",
    ro: "Medicină",
    ru: "Медицина",
    layer: 3,
  },
]
