import type { Category } from "../schema"

export const categoriesArr: Category[] = [
  {
    path: 1,
    en: "Electronics",
    ro: "Electronică",
    ru: "Электроника",
    layer: 1,
  },
  {
    path: 2,
    en: "Clothes",
    ro: "Haine",
    ru: "Одежда",
    layer: 1,
  },
  {
    path: 3,
    en: "Shoes",
    ro: "Incălțăminte",
    ru: "Обувь",
    layer: 1,
  },
  {
    path: 4,
    en: "Stationery",
    ro: "Papetărie",
    ru: "Канцелярские товары",
    layer: 1,
  },
  {
    path: 5,
    en: "Books",
    ro: "Cărți",
    ru: "Книги",
    layer: 1,
  },
  {
    path: 101,
    en: "Phones",
    ro: "Telefoane",
    ru: "Телефоны",
    layer: 2,
  },
  {
    path: 102,
    en: "Computers",
    ro: "Calculatoare",
    ru: "Компьютеры",
    layer: 2,
  },
  {
    path: 103,
    en: "Gaming consoles",
    ro: "Console de jocuri",
    ru: "Игровые консоли",
    layer: 2,
  },
  {
    path: 104,
    en: "Video equipment",
    ro: "Echipament video",
    ru: "Видеотехника",
    layer: 2,
  },
  {
    path: 105,
    en: "Headphones",
    ro: "Căști",
    ru: "Наушники",
    layer: 2,
  },
  {
    path: 106,
    en: "Accessories",
    ro: "Accesorii",
    ru: "Комплектующие",
    layer: 2,
  },
  {
    path: 201,
    en: "For men",
    ro: "A bărbaţilor",
    ru: "Мужская",
    layer: 2,
  },
  {
    path: 202,
    en: "For women",
    ro: "Femei",
    ru: "Женская",
    layer: 2,
  },
  {
    path: 203,
    en: "For children",
    ro: "Pentru copii",
    ru: "Детская",
    layer: 2,
  },
  {
    path: 204,
    en: "Unisex",
    ro: "Unisex",
    ru: "Унисекс",
    layer: 2,
  },
  {
    path: 301,
    en: "For men",
    ro: "A bărbaţilor",
    ru: "Мужская",
    layer: 2,
  },
  {
    path: 302,
    en: "For women",
    ro: "Femei",
    ru: "Женская",
    layer: 2,
  },
  {
    path: 303,
    en: "For children",
    ro: "Pentru copii",
    ru: "Детская",
    layer: 2,
  },
  {
    path: 304,
    en: "Unisex",
    ro: "Unisex",
    ru: "Унисекс",
    layer: 2,
  },
  {
    path: 401,
    en: "Writing supplies",
    ro: "Articole de papetărie",
    ru: "Письменные принадлежности",
    layer: 2,
  },
  {
    path: 402,
    en: "Paper products",
    ro: "Produse de hârtie",
    ru: "Бумажная продукция",
    layer: 2,
  },
  {
    path: 403,
    en: "Paper",
    ro: "Hârtie",
    ru: "Бумага",
    layer: 2,
  },
  {
    path: 404,
    en: "Folders and files",
    ro: "Dosare și fișiere",
    ru: "Папки и файлы",
    layer: 2,
  },
  {
    path: 405,
    en: "Office supplies",
    ro: "Articole de birou",
    ru: "Офисные принадлежности",
    layer: 2,
  },
  {
    path: 501,
    en: "Fiction",
    ro: "Literatură artistică",
    ru: "Художественная литература",
    layer: 2,
  },
  {
    path: 502,
    en: "Comics",
    ro: "Benzi desenate",
    ru: "Комиксы",
    layer: 2,
  },
  {
    path: 503,
    en: "Manga",
    ro: "Manga",
    ru: "Манга",
    layer: 2,
  },
  {
    path: 504,
    en: "Educational literature",
    ro: "Literatură didactică",
    ru: "Учебная литература",
    layer: 2,
  },
  {
    path: 10101,
    en: "Cell phones",
    ro: "Telefoane mobile",
    ru: "Мобильные",
    layer: 3,
  },
  {
    path: 10102,
    en: "Smartphones",
    ro: "Smartphone-uri",
    ru: "Смартфоны",
    layer: 3,
  },
  {
    path: 10103,
    en: "Accessories",
    ro: "Accesorii",
    ru: "Комплектующие",
    layer: 3,
  },
  {
    path: 10201,
    en: "PCs",
    ro: "PC-uri",
    ru: "ПК",
    layer: 3,
  },
  {
    path: 10202,
    en: "Laptops",
    ro: "Laptopuri",
    ru: "Ноутбуки",
    layer: 3,
  },
  {
    path: 10203,
    en: "All-in-ones",
    ro: "Monoblocuri",
    ru: "Моноблоки",
    layer: 3,
  },
  {
    path: 10204,
    en: "Tablets",
    ro: "Tablete",
    ru: "Планшеты",
    layer: 3,
  },
  {
    path: 10301,
    en: "XBOX",
    ro: "XBOX",
    ru: "XBOX",
    layer: 3,
  },
  {
    path: 10302,
    en: "PlayStation",
    ro: "PlayStation",
    ru: "PlayStation",
    layer: 3,
  },
  {
    path: 10303,
    en: "Nintendo",
    ro: "Nintendo",
    ru: "Nintendo",
    layer: 3,
  },
  {
    path: 10304,
    en: "Steam Deck",
    ro: "Steam Deck",
    ru: "Steam Deck",
    layer: 3,
  },
  {
    path: 10401,
    en: "TVs",
    ro: "Televizoare",
    ru: "Телевизоры",
    layer: 3,
  },
  {
    path: 10402,
    en: "Monitors",
    ro: "Monitoare",
    ru: "Мониторы",
    layer: 3,
  },
  {
    path: 10403,
    en: "Projectors",
    ro: "Projectoare",
    ru: "Проекторы",
    layer: 3,
  },
  {
    path: 10501,
    en: "Wired",
    ro: "Cu fir",
    ru: "Проводные",
    layer: 3,
  },
  {
    path: 10502,
    en: "Wireless",
    ro: "Fara fir",
    ru: "Беспроводные",
    layer: 3,
  },
  {
    path: 10601,
    en: "Phone cases",
    ro: "Huse pentru telefoane",
    ru: "Чехлы для телефонов",
    layer: 3,
  },
  {
    path: 10602,
    en: "Keyboards",
    ro: "Tastaturi",
    ru: "Клавиатуры",
    layer: 3,
  },
  {
    path: 10603,
    en: "Computer mice",
    ro: "Mous-uri",
    ru: "Компьютерные мыши",
    layer: 3,
  },
  {
    path: 10604,
    en: "Controllers",
    ro: "Manete de joc",
    ru: "Геймпады",
    layer: 3,
  },
  {
    path: 20101,
    en: "Shirts",
    ro: "Cămăși",
    ru: "Рубашки",
    layer: 3,
  },
  {
    path: 20102,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    path: 20103,
    en: "Pants",
    ro: "Pantaloni",
    ru: "Штаны",
    layer: 3,
  },
  {
    path: 20104,
    en: "Socks",
    ro: "Șosete",
    ru: "Носки",
    layer: 3,
  },
  {
    path: 20201,
    en: "Blouses",
    ro: "Bluze",
    ru: "Блузки",
    layer: 3,
  },
  {
    path: 20202,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    path: 20203,
    en: "Skirts",
    ro: "Fuste",
    ru: "Юбки",
    layer: 3,
  },
  {
    path: 20204,
    en: "Tights",
    ro: "Colanți",
    ru: "Колготы",
    layer: 3,
  },
  {
    path: 20301,
    en: "Shirts",
    ro: "Cămăși",
    ru: "Рубашки",
    layer: 3,
  },
  {
    path: 20302,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    path: 20303,
    en: "Pants",
    ro: "Pantaloni",
    ru: "Штаны",
    layer: 3,
  },
  {
    path: 20304,
    en: "Socks",
    ro: "Șosete",
    ru: "Носки",
    layer: 3,
  },
  {
    path: 20305,
    en: "Tights",
    ro: "Colanți",
    ru: "Колготы",
    layer: 3,
  },
  {
    path: 20401,
    en: "Shirts",
    ro: "Cămăși",
    ru: "Рубашки",
    layer: 3,
  },
  {
    path: 20402,
    en: "Jackets",
    ro: "Jachete",
    ru: "Куртки",
    layer: 3,
  },
  {
    path: 20403,
    en: "Pants",
    ro: "Pantaloni",
    ru: "Штаны",
    layer: 3,
  },
  {
    path: 20404,
    en: "Socks",
    ro: "Șosete",
    ru: "Носки",
    layer: 3,
  },
  {
    path: 30101,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    path: 30102,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    path: 30103,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    path: 30201,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    path: 30202,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    path: 30203,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    path: 30301,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    path: 30302,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    path: 30303,
    en: "Sneakers",
    ro: "Sneakers",
    ru: "Кроссовки",
    layer: 3,
  },
  {
    path: 30304,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    path: 30401,
    en: "Boots",
    ro: "Cizme",
    ru: "Ботинки",
    layer: 3,
  },
  {
    path: 30402,
    en: "Shoes",
    ro: "Pantofi",
    ru: "Туфли",
    layer: 3,
  },
  {
    path: 30403,
    en: "Sneakers",
    ro: "Sneakers",
    ru: "Кроссовки",
    layer: 3,
  },
  {
    path: 30404,
    en: "Sandals",
    ro: "Sandale",
    ru: "Сандалии",
    layer: 3,
  },
  {
    path: 40101,
    en: "Pens",
    ro: "Pixuri",
    ru: "Ручки",
    layer: 3,
  },
  {
    path: 40102,
    en: "Pencils",
    ro: "Creioane",
    ru: "Карандаши",
    layer: 3,
  },
  {
    path: 40103,
    en: "Felt-tip pens",
    ro: "Creioane colorate",
    ru: "Фломастеры",
    layer: 3,
  },
  {
    path: 40104,
    en: "Markers",
    ro: "Markere",
    ru: "Маркеры",
    layer: 3,
  },
  {
    path: 40201,
    en: "Notebooks",
    ro: "Caiete",
    ru: "Тетради",
    layer: 3,
  },
  {
    path: 40202,
    en: "Notepads",
    ro: "Blocnotes",
    ru: "Блокноты",
    layer: 3,
  },
  {
    path: 40203,
    en: "Planners",
    ro: "Planificatoare",
    ru: "Ежедневники",
    layer: 3,
  },
  {
    path: 40301,
    en: "Printer paper",
    ro: "Hârtie de imprimantă",
    ru: "Бумага для печати",
    layer: 3,
  },
  {
    path: 40302,
    en: "Colored paper",
    ro: "Hârtie colorată",
    ru: "Цветная бумага",
    layer: 3,
  },
  {
    path: 40303,
    en: "Drawing paper",
    ro: "Hârtie de desen",
    ru: "Бумага для черчения",
    layer: 3,
  },
  {
    path: 40401,
    en: "Folders",
    ro: "Dosare",
    ru: "Папки",
    layer: 3,
  },
  {
    path: 40402,
    en: "Files",
    ro: "Fișiere",
    ru: "Файлы",
    layer: 3,
  },
  {
    path: 40501,
    en: "Staplers",
    ro: "Capsator",
    ru: "Степлеры",
    layer: 3,
  },
  {
    path: 40502,
    en: "Paper punches",
    ro: "Perforatoare",
    ru: "Дыроколы",
    layer: 3,
  },
  {
    path: 40503,
    en: "Erasers",
    ro: "Gumă de șters",
    ru: "Ластики",
    layer: 3,
  },
  {
    path: 40504,
    en: "Correction fluid",
    ro: "Corectoare",
    ru: "Корректоры",
    layer: 3,
  },
  {
    path: 50101,
    en: "Sci-fi",
    ro: "SF",
    ru: "Научная фантастика",
    layer: 3,
  },
  {
    path: 50102,
    en: "Fantasy",
    ro: "Fantezie",
    ru: "Фэнтези",
    layer: 3,
  },
  {
    path: 50103,
    en: "Adventure",
    ro: "Aventură",
    ru: "Приключение",
    layer: 3,
  },
  {
    path: 50104,
    en: "Detective",
    ro: "Detectiv",
    ru: "Детектив",
    layer: 3,
  },
  {
    path: 50105,
    en: "Thriller",
    ro: "Thriller",
    ru: "Триллер",
    layer: 3,
  },
  {
    path: 50201,
    en: "Sci-fi",
    ro: "SF",
    ru: "Научная фантастика",
    layer: 3,
  },
  {
    path: 50202,
    en: "Fantasy",
    ro: "Fantezie",
    ru: "Фэнтези",
    layer: 3,
  },
  {
    path: 50203,
    en: "Adventure",
    ro: "Aventură",
    ru: "Приключение",
    layer: 3,
  },
  {
    path: 50204,
    en: "Detective",
    ro: "Detectiv",
    ru: "Детектив",
    layer: 3,
  },
  {
    path: 50205,
    en: "Thriller",
    ro: "Thriller",
    ru: "Триллер",
    layer: 3,
  },
  {
    path: 50301,
    en: "Sci-fi",
    ro: "SF",
    ru: "Научная фантастика",
    layer: 3,
  },
  {
    path: 50302,
    en: "Fantasy",
    ro: "Fantezie",
    ru: "Фэнтези",
    layer: 3,
  },
  {
    path: 50303,
    en: "Adventure",
    ro: "Aventură",
    ru: "Приключение",
    layer: 3,
  },
  {
    path: 50304,
    en: "Detective",
    ro: "Detectiv",
    ru: "Детектив",
    layer: 3,
  },
  {
    path: 50305,
    en: "Thriller",
    ro: "Thriller",
    ru: "Триллер",
    layer: 3,
  },
  {
    path: 50401,
    en: "Science",
    ro: "Ştiinţă",
    ru: "Наука",
    layer: 3,
  },
  {
    path: 50402,
    en: "Psychology",
    ro: "Psihologie",
    ru: "Психология",
    layer: 3,
  },
  {
    path: 50403,
    en: "History",
    ro: "Istorie",
    ru: "История",
    layer: 3,
  },
  {
    path: 50404,
    en: "Sociology",
    ro: "Sociologie",
    ru: "Социология",
    layer: 3,
  },
  {
    path: 50405,
    en: "Medicine",
    ro: "Medicină",
    ru: "Медицина",
    layer: 3,
  },
]
