import type { Category } from "../schema"

export const categoriesArr: Category[] = [
  {
    code: 1,
    en: "Furniture",
    ro: "Mobilă",
    ru: "Мебель",
    layer: 1,
  },
  {
    code: 101,
    en: "Soft furniture",
    ro: "Mobilier textil",
    ru: "Мягкая мебель",
    layer: 2,
  },
  {
    code: 102,
    en: "Tables and chairs",
    ro: "Mese și scaune",
    ru: "Столы и стулья",
    layer: 2,
  },
  {
    code: 103,
    en: "Office furniture",
    ro: "Mobilier de birou",
    ru: "Офисная мебель",
    layer: 2,
  },
  {
    code: 104,
    en: "Storage furniture",
    ro: "Mobilier de depozitare",
    ru: "Мебель для хранения",
    layer: 2,
  },
  {
    code: 105,
    en: "Accessories",
    ro: "Accesorii",
    ru: "Комплектующие",
    layer: 2,
  },
  {
    code: 10101,
    en: "Sofas",
    ro: "Canapele",
    ru: "Диваны",
    layer: 3,
  },
  {
    code: 10102,
    en: "Armchairs",
    ro: "Fotolii",
    ru: "Кресла",
    layer: 3,
  },
  {
    code: 10201,
    en: "Chairs",
    ro: "Scaune",
    ru: "Стулья",
    layer: 3,
  },
  {
    code: 10202,
    en: "Tables",
    ro: "Mese",
    ru: "Столы",
    layer: 3,
  },
  {
    code: 10203,
    en: "Stools",
    ro: "Scăunele",
    ru: "Табуреты",
    layer: 3,
  },
  {
    code: 10301,
    en: "Armchairs",
    ro: "Fotolii",
    ru: "Кресла",
    layer: 3,
  },
  {
    code: 10302,
    en: "Tables",
    ro: "Mese",
    ru: "Столы",
    layer: 3,
  },
  {
    code: 10303,
    en: "Chairs",
    ro: "Scaune",
    ru: "Стулья",
    layer: 3,
  },
  {
    code: 10401,
    en: "Cabinets",
    ro: "Dulapuri",
    ru: "Шкафы",
    layer: 3,
  },
  {
    code: 10402,
    en: "Drawers",
    ro: "Comode",
    ru: "Комоды",
    layer: 3,
  },
  {
    code: 10403,
    en: "Nightstands",
    ro: "Noptiere",
    ru: "Тумбы",
    layer: 3,
  },
  {
    code: 10501,
    en: "Hangers",
    ro: "Aragazuri",
    ru: "Вешалки",
    layer: 3,
  },
  {
    code: 10502,
    en: "Shoe racks",
    ro: "Rafturi pentru pantofi",
    ru: "Полки для обуви",
    layer: 3,
  },
]
