import { CharacteristicsFurniture } from "../schema"

export const characteristicsFurnitureArr: CharacteristicsFurniture[] = [
  {
    vendor_code: "10101/",
    color: "",
    material: "",
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    folding: true,
    warranty: 0,
  },
  {
    vendor_code: "10101/1/base",
    color: "beige",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/1/v1-1",
    color: "burgundy",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/1/v1-2",
    color: "green",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/1/v1-3",
    color: "blue",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/base",
    color: "light-beige",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/v1-1",
    color: "turquoise",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/v1-2",
    color: "green",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/v1-3",
    color: "blue",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/base",
    color: "pink",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/v1-1",
    color: "beige",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/v1-2",
    color: "light-gray",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/v1-3",
    color: "yellow",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/4/base",
    color: "gray",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/4/v1-1",
    color: "yellow",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/4/v1-2",
    color: "brown",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/4/v1-3",
    color: "beige",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/5/base",
    color: "dark_gray",
    material: "micro_velvet",
    width: 210,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v3-1",
    color: "dark_gray",
    material: "micro_velvet",
    width: 150,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v3-2",
    color: "dark_gray",
    material: "micro_velvet",
    width: 170,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v3-3",
    color: "dark_gray",
    material: "micro_velvet",
    width: 185,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1",
    color: "gray",
    material: "micro_velvet",
    width: 210,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1_3-1",
    color: "gray",
    material: "micro_velvet",
    width: 150,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1_3-2",
    color: "gray",
    material: "micro_velvet",
    width: 170,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1_3-3",
    color: "gray",
    material: "micro_velvet",
    width: 185,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2",
    color: "beige",
    material: "micro_velvet",
    width: 210,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2_3-1",
    color: "beige",
    material: "micro_velvet",
    width: 150,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2_3-2",
    color: "beige",
    material: "micro_velvet",
    width: 170,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2_3-3",
    color: "beige",
    material: "micro_velvet",
    width: 185,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/base",
    color: "gray",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/v1-1",
    color: "blue",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/v1-2",
    color: "green",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/v1-3",
    color: "beige",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/7/base",
    color: "zebra",
    material: "velvet",
    width: 210,
    height: 102,
    depth: 92,
    weight: 20,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10101/8/base",
    color: "blue",
    material: "Micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 15,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/8/v1-1",
    color: "gray",
    material: "Micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 15,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/8/v1-2",
    color: "brown",
    material: "Micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 15,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/9/base",
    color: "",
    material: "",
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    folding: true,
    warranty: 0,
  },
  {
    vendor_code: "10101/",
    color: "",
    material: "",
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    folding: true,
    warranty: 0,
  },
]
