import { CharacteristicsFurniture } from "../schema"

export const characteristicsFurnitureArr: CharacteristicsFurniture[] = [
  {
    vendor_code: "10101/",
    color: "",
    material: "",
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    folding: true,
    warranty: 0,
  },
  {
    vendor_code: "10101/1/base",
    color: "beige",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/1/v1-1",
    color: "burgundy",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/1/v1-2",
    color: "green",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/1/v1-3",
    color: "blue",
    material: "micro_velvet",
    width: 241,
    height: 94,
    depth: 108,
    weight: 15,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/base",
    color: "light-beige",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/v1-1",
    color: "turquoise",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/v1-2",
    color: "green",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/2/v1-3",
    color: "blue",
    material: "micro_velvet",
    width: 219,
    height: 92,
    depth: 107,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/base",
    color: "pink",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/v1-1",
    color: "beige",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/v1-2",
    color: "light-gray",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/3/v1-3",
    color: "yellow",
    material: "micro_velvet",
    width: 155,
    height: 84,
    depth: 85,
    weight: 12,
    folding: true,
    warranty: 18,
  },
  {
    vendor_code: "10101/4/base",
    color: "gray",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/4/v1-1",
    color: "yellow",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/4/v1-2",
    color: "brown",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/4/v1-3",
    color: "beige",
    material: "micro_velvet",
    width: 223,
    height: 84,
    depth: 150,
    weight: 20,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10101/5/base",
    color: "dark_gray",
    material: "micro_velvet",
    width: 210,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v3-1",
    color: "dark_gray",
    material: "micro_velvet",
    width: 150,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v3-2",
    color: "dark_gray",
    material: "micro_velvet",
    width: 170,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v3-3",
    color: "dark_gray",
    material: "micro_velvet",
    width: 185,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1",
    color: "gray",
    material: "micro_velvet",
    width: 210,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1_3-1",
    color: "gray",
    material: "micro_velvet",
    width: 150,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1_3-2",
    color: "gray",
    material: "micro_velvet",
    width: 170,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-1_3-3",
    color: "gray",
    material: "micro_velvet",
    width: 185,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2",
    color: "beige",
    material: "micro_velvet",
    width: 210,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2_3-1",
    color: "beige",
    material: "micro_velvet",
    width: 150,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2_3-2",
    color: "beige",
    material: "micro_velvet",
    width: 170,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/5/v1-2_3-3",
    color: "beige",
    material: "micro_velvet",
    width: 185,
    height: 88,
    depth: 100,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/base",
    color: "gray",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/v1-1",
    color: "blue",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/v1-2",
    color: "green",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/6/v1-3",
    color: "beige",
    material: "flock",
    width: 220,
    height: 73,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/7/base",
    color: "zebra",
    material: "velvet",
    width: 210,
    height: 102,
    depth: 92,
    weight: 20,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10101/8/base",
    color: "blue",
    material: "Micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 15,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/8/v1-1",
    color: "gray",
    material: "Micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 15,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/8/v1-2",
    color: "brown",
    material: "Micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 15,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/9/base",
    color: "yellow",
    material: "eco-leather",
    width: 80,
    height: 63,
    depth: 76,
    weight: 10,
    folding: false,
    warranty: 18,
  },
  {
    vendor_code: "10101/9/v1-1",
    color: "black",
    material: "eco-leather",
    width: 80,
    height: 63,
    depth: 76,
    weight: 10,
    folding: false,
    warranty: 18,
  },
  {
    vendor_code: "10101/9/v1-2",
    color: "blue",
    material: "eco-leather",
    width: 80,
    height: 63,
    depth: 76,
    weight: 10,
    folding: false,
    warranty: 18,
  },
  {
    vendor_code: "10101/9/v1-3",
    color: "beige",
    material: "eco-leather",
    width: 80,
    height: 63,
    depth: 76,
    weight: 10,
    folding: false,
    warranty: 18,
  },
  {
    vendor_code: "10101/10/base",
    color: "blue",
    material: "micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 18,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/10/v1-1",
    color: "brown",
    material: "micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 18,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/10/v1-2",
    color: "beige",
    material: "micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 18,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/10/v1-3",
    color: "gray",
    material: "micro-flock",
    width: 210,
    height: 92,
    depth: 92,
    weight: 18,
    folding: true,
    warranty: 24,
  },
  {
    vendor_code: "10101/11/base",
    color: "light-brown",
    material: "matting",
    width: 210,
    height: 102,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10101/11/v1-1",
    color: "light-beige",
    material: "matting",
    width: 210,
    height: 102,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10101/11/v1-2",
    color: "brown",
    material: "matting",
    width: 210,
    height: 102,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10101/11/v1-3",
    color: "gray",
    material: "matting",
    width: 210,
    height: 102,
    depth: 92,
    weight: 25,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10101/12/base",
    color: "gray",
    material: "velvet",
    width: 210,
    height: 102,
    depth: 92,
    weight: 20,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10101/12/v1-1",
    color: "green",
    material: "velvet",
    width: 210,
    height: 102,
    depth: 92,
    weight: 20,
    folding: true,
    warranty: 16,
  },
  {
    vendor_code: "10102/1/base",
    color: "dark-beige",
    material: "micro_velvet",
    width: 75,
    height: 85,
    depth: 85,
    weight: 23,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10102/1/v1-1",
    color: "blue",
    material: "micro_velvet",
    width: 75,
    height: 85,
    depth: 85,
    weight: 23,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10102/1/v1-2",
    color: "yellow",
    material: "micro_velvet",
    width: 75,
    height: 85,
    depth: 85,
    weight: 23,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10102/1/v1-3",
    color: "brown",
    material: "micro_velvet",
    width: 75,
    height: 85,
    depth: 85,
    weight: 23,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10102/2/base",
    color: "green",
    material: "matting",
    width: 77,
    height: 98,
    depth: 90,
    weight: 22,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/2/v1-1",
    color: "blue",
    material: "matting",
    width: 77,
    height: 98,
    depth: 90,
    weight: 22,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/2/v1-2",
    color: "white",
    material: "matting",
    width: 77,
    height: 98,
    depth: 90,
    weight: 22,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/2/v1-3",
    color: "red",
    material: "matting",
    width: 77,
    height: 98,
    depth: 90,
    weight: 22,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/3/base",
    color: "gray",
    material: "matting",
    width: 90,
    height: 90,
    depth: 87,
    weight: 18,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10102/3/v1-1",
    color: "beige",
    material: "matting",
    width: 90,
    height: 90,
    depth: 87,
    weight: 18,
    folding: true,
    warranty: 12,
  },
  {
    vendor_code: "10102/4/base",
    color: "beige",
    material: "eco-leather",
    width: 60,
    height: 74,
    depth: 60,
    weight: 15,
    folding: false,
    warranty: 6,
  },
  {
    vendor_code: "10102/5/base",
    color: "light-gray",
    material: "matting",
    width: 64,
    height: 91,
    depth: 78,
    weight: 12,
    folding: false,
    warranty: 18,
  },
  {
    vendor_code: "10102/5/v1-1",
    color: "light-brown",
    material: "matting",
    width: 64,
    height: 91,
    depth: 78,
    weight: 12,
    folding: false,
    warranty: 18,
  },

  {
    vendor_code: "10102/6/base",
    color: "red",
    material: "eco-leather",
    width: 90,
    height: 78,
    depth: 68,
    weight: 15,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/6/v1-1",
    color: "brown",
    material: "eco-leather",
    width: 90,
    height: 78,
    depth: 68,
    weight: 15,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/6/v1-2",
    color: "blue",
    material: "eco-leather",
    width: 90,
    height: 78,
    depth: 68,
    weight: 15,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/6/v1-3",
    color: "green",
    material: "eco-leather",
    width: 90,
    height: 78,
    depth: 68,
    weight: 15,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/7/base",
    color: "brown",
    material: "matting",
    width: 90,
    height: 92,
    depth: 80,
    weight: 25,
    folding: false,
    warranty: 16,
  },
  {
    vendor_code: "10102/8/base",
    color: "black",
    material: "textile",
    width: 55,
    height: 77,
    depth: 50,
    weight: 1,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/8/v1-1",
    color: "dark-blue",
    material: "textile",
    width: 55,
    height: 77,
    depth: 50,
    weight: 1,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/8/v1-2",
    color: "gray",
    material: "textile",
    width: 55,
    height: 77,
    depth: 50,
    weight: 1,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10102/9/base",
    color: "beige",
    material: "matting",
    width: 67,
    height: 100,
    depth: 80,
    weight: 13,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/1/base",
    color: "light-gray",
    material: "cloth",
    width: 51,
    height: 69,
    depth: 58,
    weight: 8,
    folding: false,
    warranty: 6,
  },
  {
    vendor_code: "10201/1/v1-1",
    color: "gray",
    material: "cloth",
    width: 51,
    height: 69,
    depth: 58,
    weight: 8,
    folding: false,
    warranty: 6,
  },
  {
    vendor_code: "10201/2/base",
    color: "white",
    material: "wood",
    width: 40,
    height: 91,
    depth: 53,
    weight: 7,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/2/v1-1",
    color: "brown",
    material: "wood",
    width: 40,
    height: 91,
    depth: 53,
    weight: 7,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/2/v1-2",
    color: "black",
    material: "wood",
    width: 40,
    height: 91,
    depth: 53,
    weight: 7,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/2/v1-3",
    color: "beige",
    material: "wood",
    width: 40,
    height: 91,
    depth: 53,
    weight: 7,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/3/base",
    color: "black",
    material: "micro_velvet",
    width: 56,
    height: 85,
    depth: 52,
    weight: 4,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/3/v1-1",
    color: "beige",
    material: "micro_velvet",
    width: 56,
    height: 85,
    depth: 52,
    weight: 4,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/3/v1-2",
    color: "black",
    material: "micro_velvet",
    width: 56,
    height: 85,
    depth: 52,
    weight: 4,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/3/v1-3",
    color: "gray",
    material: "micro_velvet",
    width: 56,
    height: 85,
    depth: 52,
    weight: 4,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/4/base",
    color: "gray",
    material: "micro_velvet",
    width: 47,
    height: 93,
    depth: 51,
    weight: 4,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/5/base",
    color: "gray",
    material: "eco-leather",
    width: 46,
    height: 110,
    depth: 54,
    weight: 7,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/5/v1-1",
    color: "blue",
    material: "eco-leather",
    width: 46,
    height: 110,
    depth: 54,
    weight: 7,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/5/v1-2",
    color: "purple",
    material: "eco-leather",
    width: 46,
    height: 110,
    depth: 54,
    weight: 7,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/5/v1-3",
    color: "white",
    material: "eco-leather",
    width: 46,
    height: 110,
    depth: 54,
    weight: 7,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/6/base",
    color: "gray",
    material: "velvet",
    width: 59,
    height: 88,
    depth: 50,
    weight: 7,
    folding: false,
    warranty: 12,
  },
  {
    vendor_code: "10201/7/base",
    color: "black",
    material: "velvet",
    width: 44,
    height: 89,
    depth: 40,
    weight: 5,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/7/v1-1",
    color: "green",
    material: "velvet",
    width: 44,
    height: 89,
    depth: 40,
    weight: 5,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/7/v1-2",
    color: "yellow",
    material: "velvet",
    width: 44,
    height: 89,
    depth: 40,
    weight: 5,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/7/v1-3",
    color: "brown",
    material: "velvet",
    width: 44,
    height: 89,
    depth: 40,
    weight: 5,
    folding: false,
    warranty: 24,
  },
  {
    vendor_code: "10201/8/base",
    color: "black",
    material: "eco-leather",
    width: 42,
    height: 98,
    depth: 41,
    weight: 5,
    folding: false,
    warranty: 6,
  },
  {
    vendor_code: "10201/9/base",
    color: "pink",
    material: "velvet",
    width: 46,
    height: 80,
    depth: 48,
    weight: 3,
    folding: false,
    warranty: 1,
  },
  {
    vendor_code: "10201/10/base",
    color: "beige",
    material: "eco-leather",
    width: 52,
    height: 91,
    depth: 38,
    weight: 4,
    folding: false,
    warranty: 6,
  },
  {
    vendor_code: "10201/10/v1-1",
    color: "brown",
    material: "eco-leather",
    width: 52,
    height: 91,
    depth: 38,
    weight: 4,
    folding: false,
    warranty: 6,
  },
  {
    vendor_code: "10201/10/v1-2",
    color: "white",
    material: "eco-leather",
    width: 52,
    height: 91,
    depth: 38,
    weight: 4,
    folding: false,
    warranty: 6,
  },
  {
    vendor_code: "10202//base",
    color: "",
    material: "",
    width: 0,
    height: 0,
    depth: 0,
    weight: 0,
    folding: false,
    warranty: 0,
  },
]
