import { Colors } from "../schema"

export const colorsArr: Colors[] = [
  { name: "beige", en: "beige", ro: "bej", ru: "бежевый", hex: "#F5F5DC" },
  {
    name: "burgundy",
    en: "burgundy",
    ro: "burgund",
    ru: "бордовый",
    hex: "#800020",
  },
  { name: "green", en: "green", ro: "verde", ru: "зеленый", hex: "#008000" },
  { name: "blue", en: "blue", ro: "albastru", ru: "синий", hex: "#0000FF" },
  {
    name: "light-beige",
    en: "light beige",
    ro: "bej deschis",
    ru: "светло-бежевый",
    hex: "#F5F5DC",
  },
  {
    name: "turquoise",
    en: "turquoise",
    ro: "turcoaz",
    ru: "бирюзовый",
    hex: "#40E0D0",
  },
  { name: "pink", en: "pink", ro: "roz", ru: "розовый", hex: "#FFC0CB" },
  {
    name: "light-gray",
    en: "light gray",
    ro: "gri deschis",
    ru: "светло-серый",
    hex: "#D3D3D3",
  },
  { name: "yellow", en: "yellow", ro: "galben", ru: "желтый", hex: "#FFFF00" },
  { name: "gray", en: "gray", ro: "gri", ru: "серый", hex: "#808080" },
  { name: "brown", en: "brown", ro: "maro", ru: "коричневый", hex: "#A52A2A" },
  {
    name: "dark-gray",
    en: "dark gray",
    ro: "gri inchis",
    ru: "темно-серый",
    hex: "#A9A9A9",
  },
  {
    name: "zebra",
    en: "zebra",
    ro: "zebră",
    ru: "зебра",
    hex: "#FFFFFF,#000000",
  },
  { name: "black", en: "black", ro: "negru", ru: "черный", hex: "#000000" },
  {
    name: "light-brown",
    en: "light brown",
    ro: "maro deschis",
    ru: "светло-коричневый",
    hex: "#D2B48C",
  },
  {
    name: "dark-beige",
    en: "dark beige",
    ro: "bej inchis",
    ru: "темно-бежевый",
    hex: "#A9A9A9",
  },
  { name: "white", en: "white", ro: "alb", ru: "белый", hex: "#FFFFFF" },
  { name: "red", en: "red", ro: "roșu", ru: "красный", hex: "#FF0000" },
  {
    name: "dark-blue",
    en: "dark blue",
    ro: "albastru inchis",
    ru: "темно-синий",
    hex: "#00008B",
  },
  { name: "purple", en: "purple", ro: "mov", ru: "пурпурный", hex: "#800080" },
]
