import { ItemsDescription } from "../schema"

export const itemsDescriptionArr: ItemsDescription[] = [
  {
    vendor_code: "10101-1-c0m0w0h0d0",
    en: `The sofa can be comfortably slept on without disassembling it. In its unfolded state, the sofa forms a spacious sleeping area. The sofa is equipped with a storage box for bedding.`,
    ro: `Pe canapea se poate dormi confortabil fără să o desfășurați. În forma sa desfășurată, canapeaua formează un spațiu generos pentru dormit. Canapeaua este echipată cu o cutie de depozitare pentru lenjerie de pat.`,
    ru: `На диване можно комфортно спать, не разбирая его. В разложенном виде диван образует просторное спальное место. Диван оснащен бельевым коробом.`,
  },
  {
    vendor_code: "10101-2-c0m0w0h0d0",
    en: `You can always put your phone on the armrest tabletop and place a cup of tea there. In its unfolded state, the sofa forms a spacious sleeping area. The sofa is equipped with a storage box for bedding.`,
    ro: `Întotdeauna puteți pune telefonul pe blatul de la cotieră și puteți pune o ceașcă de ceai acolo. În forma sa desfășurată, canapeaua formează un spațiu generos pentru dormit. Canapeaua este echipată cu o cutie de depozitare pentru lenjerie de pat.`,
    ru: `На столешницу подлокотника всегда можно положить телефон и поставить чашечку чая. В разложенном виде диван образует просторное спальное место. Диван оснащен бельевым коробом.`,
  },
  {
    vendor_code: "10101-3-c0m0w0h0d0",
    en: `The sofa will fit seamlessly into the interior of a modern urban apartment. Thanks to its compact size, it will also make an excellent addition to a child's room or kitchen.`,
    ro: `Canapeaua se va integra perfect în interiorul unui apartament urban modern. Datorită dimensiunilor sale compacte, va fi de asemenea un excelent adaos pentru camera unui copil sau pentru bucătărie.`,
    ru: `Диван удачно впишется в обстановку современной городской квартиры. Благодаря компактным размерам он также станет отличным дополнением детской комнаты или кухни`,
  },
  {
    vendor_code: "10101-4-c0m0w0h0d0",
    en: `The sofa section allows you to take a semi-reclining position on the couch. Beneath this section, there is a spacious storage box for linens. When unfolded, the sofa forms a generous sleeping area.`,
    ro: `Secțiunea de canapea vă permite să adoptați o poziție semireclinată pe canapea. Sub această secțiune, se află o cutie spațioasă pentru lenjerie. Când este desfăcut, canapeaua devine un spațiu generos pentru dormit.`,
    ru: `Секция канапе позволяет принять на диване положение полулежа. Под данной секцией расположен вместительный бельевой короб. В разложенном виде диван образует просторное спальное место.`,
  },
  {
    vendor_code: "10101-5-c0m0w0h0d0",
    en: `The information about the technical specifications, package contents, country of manufacture, appearance, and color of the product is for reference purposes and is c0m0w0h0d0d on the latest available information at the time of publication.`,
    ro: `Informațiile despre specificațiile tehnice, conținutul pachetului, țara de fabricație, aspectul și culoarea produsului sunt cu titlu de referință și se bazează pe cele mai recente informații disponibile la momentul publicării.`,
    ru: `Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях`,
  },
  {
    vendor_code: "10101-6-c0m0w0h0d0",
    en: `The model's advantage lies in its original design in the spirit of the latest European trends, making it harmoniously blend into any interior. The flock upholstery is low-maintenance, pleasant to the touch, and durable.`,
    ro: `Avantajul modelului este designul original în spiritul ultimelor tendințe europene, deci arată armonios în orice interior. Tapițeria de turmă este nemaipomenită în îngrijire, plăcută la atingere și rezistentă la uzură.`,
    ru: `Достоинство модели — оригинальный дизайн в духе последних европейских трендов, поэтому она гармонично выглядит в любом интерьере. Обивка флок неприхотлива в уходе, приятна на ощупь и износоустойчива.`,
  },
  {
    vendor_code: "10101-7-c0m0w0h0d0",
    en: `The model has a sturdy frame designed for intense daily loads, a safe filler that easily restores its shape, and unpretentious upholstery.`,
    ro: `Modelul are un cadru robust conceput pentru sarcini zilnice intense, o umplutură sigură care își restabilește cu ușurință forma și o tapițerie nepretențioasă.`,
    ru: `У модели прочный каркас, рассчитанный на интенсивные ежедневные нагрузки, безопасный наполнитель, легко восстанавливающий форму, и неприхотливая в уходе обивка`,
  },
  {
    vendor_code: "10101-8-c0m0w0h0d0",
    en: `This model can be placed along any wall or in the center - it all depends on the concept of the interior.`,
    ro: `Acest model poate fi plasat de-a lungul oricărui perete sau în centru - totul depinde de conceptul interiorului.`,
    ru: `Данную модель можно поставить как вдоль любой стены, так и по центру — все зависит от концепции интерьера.`,
  },
  {
    vendor_code: "10101-9-c0m0w0h0d0",
    en: `The straight sofa will be the perfect solution for arranging waiting areas, reception areas, or workspaces. Your guests and employees will appreciate the comfort and style of this wonderful piece of furniture.`,
    ro: `Canapeaua dreaptă va fi soluția perfectă pentru amenajarea zonelor de așteptare, a zonelor de primire sau a spațiilor de lucru. Oaspeții și angajații dvs. vor aprecia confortul și stilul acestui minunat obiect de mobilier.`,
    ru: `Прямой диван станет идеальным решением для обустройства зоны ожидания, приемной или рабочего пространства. Ваши гости и сотрудники оценят комфорт и стиль этого замечательного предмета мебели.`,
  },
  {
    vendor_code: "10101-10-c0m0w0h0d0",
    en: `The Olympus sofa is a popular classic model with optimal dimensions, which makes it look great even in a small space. It can be placed along any wall or in the center, depending on the interior concept.`,
    ro: `Canapeaua Olympus este un model clasic popular, cu dimensiuni optime, ceea ce o face să arate excelent chiar și într-un spațiu mic. Poate fi plasată de-a lungul oricărei pereți sau în centrul încăperii, în funcție de conceptul interior.`,
    ru: `Диван Олимп — популярная классическая модель с оптимальными габаритами, благодаря которым отлично смотрится даже в небольшом помещении. Ее можно поставить как вдоль любой стены, так и по центру — все зависит от концепции интерьера.`,
  },
  {
    vendor_code: "10101-11-c0m0w0h0d0",
    en: `The model features a sturdy frame designed for intensive daily use, safe filler that easily regains its shape, and low-maintenance upholstery.`,
    ro: `Modelul prezintă un cadru rezistent conceput pentru utilizare intensivă zilnică, umplutură sigură ce își redobândește ușor forma și tapițerie ușor de întreținut.`,
    ru: `У модели прочный каркас , рассчитанный на интенсивные ежедневные нагрузки, безопасный наполнитель, легко восстанавливающий форму, и неприхотливая в уходе обивка.`,
  },
  {
    vendor_code: "10101-12-c0m0w0h0d0",
    en: `The "Comfort" sofa is a modern solution with an optimal balance of cost and quality. The model features a sturdy frame designed for intensive daily use, safe filler that easily regains its shape, and low-maintenance upholstery.`,
    ro: `Canapeaua "Comfort" reprezintă o soluție modernă cu un echilibru optim între cost și calitate. Modelul dispune de un cadru solid, proiectat pentru utilizare intensivă zilnică, umplutură sigură care își recâștigă ușor forma și tapițerie ușor de întreținut.`,
    ru: `Диван "Комфорт"  — современное решение с оптимальным соотношением стоимости и качества. У модели прочный каркас, рассчитанный на интенсивные ежедневные нагрузки, безопасный наполнитель, легко восстанавливающий форму, и неприхотливая в уходе обивка.`,
  },
  {
    vendor_code: "10102-1-c0m0w0h0d0",
    en: `The c0m0w0h0d0 of the chair is a metal frame with orthopedic slats. Thanks to the sturdy metal frame, the chair can withstand loads up to 200 kg. Flexible wooden slats provide good air circulation and a springy effect.`,
    ro: `Baza scaunului este un cadru metalic cu lamele ortopedice. Datorită cadrului metalic rezistent, scaunul poate suporta încărcături de până la 200 kg. Lamele de lemn flexibile asigură o bună circulație a aerului și un efect elastic.`,
    ru: `Основа кресла — металлокаркас с ортопедическими ламелями. Благодаря прочному металлическому каркасу кресло выдерживает нагрузку до 200 кг. Гибкие деревянные ламели обеспечивают хорошую циркуляцию воздуха и пружинящий эффект.`,
  },
  {
    vendor_code: "10102-2-c0m0w0h0d0",
    en: `The cozy armchair on legs "Fantazer" will fit perfectly into any modern home or office interior.`,
    ro: `Fotoliul confortabil pe picioare "Fantazer" se va integra perfect în orice interior modern de acasă sau de birou.`,
    ru: `Уютное интерьерное кресло на ножках Фантазер прекрасно впишется в любой современный домашний или офисный интерьер.`,
  },
  {
    vendor_code: "10102-3-c0m0w0h0d0",
    en: `The color of the upholstery depends on the batch of fabric and can vary from delicate to saturated.`,
    ro: `Culoarea tapiteriei depinde de lotul de material textil și poate varia de la delicată la saturată.`,
    ru: `Цвет обивки зависит от партии ткани и может варьироваться от нежного до насыщенного.`,
  },
  {
    vendor_code: "10102-4-c0m0w0h0d0",
    en: `It will be perfect for any office or will adorn the interior of your living room, bedroom, study, or any room, providing comfort and coziness in your home.`,
    ro: `Va fi perfect pentru orice birou sau va împodobi interiorul livingului, dormitorului, biroului, sau oricărei încăperi, oferind confort și intimitate în casa dvs.`,
    ru: `Идеально подойдет для любого офиса или украсит интерьер Вашей гостиной, спальни, комнаты, кабинета, обеспечит комфорт и уют в Вашем доме.`,
  },
  {
    vendor_code: "10102-5-c0m0w0h0d0",
    en: `The unique armchair with a backrest will instantly transform your interior and provide 100% comfort.`,
    ro: `Fotoliul unic cu spătarul va transforma instantaneu interiorul dumneavoastră și va oferi 100% confort`,
    ru: `Уникальное кресло со спинкой моментально преобразит ваш интерьер и обеспечит 100% комфорт.`,
  },
  {
    vendor_code: "10102-6-c0m0w0h0d0",
    en: `The straight office chair is compact and small in size, making it a versatile solution for various spaces.`,
    ro: `Scaunul de birou drept este compact și de dimensiuni mici, ceea ce-l face o soluție versatilă pentru diferite spații.`,
    ru: `Кресло прямое офисное – компактное и малогабаритное, что делает его универсальным решением для разных помещений.`,
  },
  {
    vendor_code: "10102-7-c0m0w0h0d0",
    en: `This model looks luxurious, withstands heavy loads without compressing the filler and deforming the frame.`,
    ro: `Această model arată luxos, rezistă la încărcături mari fără a comprima umplutura și a deforma cadru.`,
    ru: `Данная модель роскошно выглядит, выдерживает большие нагрузки без продавливания наполнителя и деформации каркаса. `,
  },
  {
    vendor_code: "10102-8-c0m0w0h0d0",
    en: `The cover is made of cotton and polyester with added viscose and linen. It's a durable and comfortable cover with a simple pattern.`,
    ro: `Husa este fabricată din bumbac și poliester cu adaos de viscoză și in. Este o husă durabilă și confortabilă, cu un model simplu.`,
    ru: `Чехол изготовлен из хлопка и полиэстера с добавлением вискозы и льна. Прочный и комфортный чехол с простым рисунком.`,
  },
  {
    vendor_code: "10102-9-c0m0w0h0d0",
    en: `This is safe furniture for a child's room and comfortable furniture for an adult's room, as the armchair does not have sharp corners.`,
    ro: `Aceasta este o mobilă sigură pentru camera copilului și mobilă confortabilă pentru camera unui adult, deoarece fotoliul nu are colțuri ascuțite.`,
    ru: `Это безопасная мебель в детскую комнату и комфортная мебель для комнаты взрослых, так как кресло не имеет острых углов.`,
  },
  {
    vendor_code: "10201-1-c0m0w0h0d0",
    en: `An elegant fusion of classic and modern design with a curved backrest that combines the functions of both a backrest and armrest.`,
    ro: `Un echilibru elegant între clasic și modern, cu un spătar încovoiat care îmbină funcțiile de spătar și suport pentru brațe.`,
    ru: `Элегантный симбиоз классики и современности с изогнутой спинкой, совмещающей в себе функции подлокотника.`,
  },
  {
    vendor_code: "10201-2-c0m0w0h0d0",
    en: `During the chair's production, the most environmentally friendly and durable material for furniture manufacturing was used – solid pine wood, which looks even better over time.`,
    ro: `În timpul producției scaunului, s-a folosit cel mai prietenos și durabil material pentru fabricarea mobilei - lemnul masiv de pin, care arată și mai bine în timp.`,
    ru: `При производстве стула использован наиболее экологичный и прочный материал для производства мебели – массив сосны, который со временем выглядит только лучше.`,
  },
  {
    vendor_code: "10201-3-c0m0w0h0d0",
    en: `This comfortable chair with soft seat and backrest will be a great addition to any room in your home.`,
    ro: `Acest scaun confortabil cu șezut și spătar moale va fi o excelentă completare pentru orice cameră din casa dvs.`,
    ru: `Этот комфортный стул с мягкими сиденьем и спинкой станет отличным дополнением для любой комнаты вашего дома. `,
  },
  {
    vendor_code: "10201-4-c0m0w0h0d0",
    en: `The rounded slightly concave backrest is an unusual solution that not only gives the chair a designer look but also creates an optimally comfortable position for your back.`,
    ro: `Spătarul rotunjit ușor concav este o soluție neobișnuită care nu numai că conferă scaunului un aspect de designer, dar creează și o poziție optim de confortabilă pentru spatele dumneavoastră.`,
    ru: `Округлая чуть вогнутая спинка - необычное решение, которое не только придает стулу дизайнерский вид, но и создает оптимально комфортное положение для Вашей спины.`,
  },
  {
    vendor_code: "10201-5-c0m0w0h0d0",
    en: `The seat is of a curved shape, soft, with a soft backrest. The c0m0w0h0d0 is made of sturdy metal. There is a swivel mechanism.`,
    ro: `Scaunul are un șezut de formă curbată, moale, cu un spătar moale. Baza este realizată din metal rezistent. Există un mecanism de rotire.`,
    ru: `Сиденье фигурной формы, мягкое, с мягкой спинкой. Основание сделано из прочного металла. Есть механизм вращения.`,
  },
  {
    vendor_code: "10201-6-c0m0w0h0d0",
    en: `The chair is made of durable metal, ensuring its longevity and reliability.`,
    ro: `Scaunul este fabricat din metal rezistent, asigurându-i longevitatea și fiabilitatea.`,
    ru: `Стул изготовлен из прочного металла, что гарантирует его долговечность и надежность.`,
  },
  {
    vendor_code: "10201-7-c0m0w0h0d0",
    en: `Milana chairs are made of multi-layered plywood and a solid steel frame.`,
    ro: `Scaunele Milana sunt fabricate din furnir multistrat și un cadru integral din oțel.`,
    ru: `Стулья Милана изготовлены из многослойной фанеры и стального цельнометаллического каркаса.`,
  },
  {
    vendor_code: "10201-8-c0m0w0h0d0",
    en: `Stylish appearance combined with practical function.`,
    ro: `Aspect elegant combinat cu funcție practică.`,
    ru: `Стильный внешний вид в сочетании с практичной функцией.`,
  },
  {
    vendor_code: "10201-9-c0m0w0h0d0",
    en: `This exquisite pink chair is made of high-quality velvet material, which gives it an elegant and luxurious appearance.`,
    ro: `Acest scaun roz exquisit este fabricat din material de catifea de înaltă calitate, ceea ce îi conferă un aspect elegant și luxos.`,
    ru: `Этот восхитительный розовый стул выполнен из высококачественного бархатного материала, который придает ему элегантный и роскошный вид.`,
  },
  {
    vendor_code: "10201-10-",
    en: `The information about the technical specifications, package contents, country of manufacture, appearance, and color of the product is for reference purposes and is c0m0w0h0d0d on the latest available information at the time of publication.`,
    ro: `Informațiile despre specificațiile tehnice, conținutul pachetului, țara de fabricație, aspectul și culoarea produsului sunt cu titlu de referință și se bazează pe cele mai recente informații disponibile la momentul publicării.`,
    ru: `Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях`,
  },
  {
    vendor_code: "10202-1-c0m0w0h0d0",
    en: `The table is equipped with a gas lift swivel mechanism.`,
    ro: `Masa este echipată cu un mecanism de ridicare cu gaz și pivotare.`,
    ru: `Стол снабжен поворотно-подъемным механизмом газ-лифт.`,
  },
  {
    vendor_code: "10202-2-c0m0w0h0d0",
    en: `Multifunctional – can be used as a coffee table or bedside table. Compact – doesn't take up much space, perfect for small-sized apartments. Stylish – white color, original design, round tabletop.`,
    ro: `Multifuncțional - poate fi folosit ca masă de cafea sau masă de noapte. Compact - nu ocupă mult spațiu, perfect pentru apartamentele mici ca suprafață. Elegant - culoare albă, design original, blat de masă rotund.`,
    ru: `Многофункциональный – может использоваться как журнальный или прикроватный. Компактный – не занимает много места, идеальный выбор для небольших по площади квартир. Стильный – белый цвет, оригинальный дизайн, круглая столешница.`,
  },
  {
    vendor_code: "10202-3-c0m0w0h0d0",
    en: `Kitchen table with high-quality tempered glass coating, practical, durable, heavy.`,
    ro: `Masă de bucătărie cu acoperire din sticlă temperată de înaltă calitate, practică, durabilă, grea.`,
    ru: `Стол кухонный с покрытием из закалённого стекла отличного качества, практичный, устойчивый, тяжелый.`,
  },
  {
    vendor_code: "10202-4-c0m0w0h0d0",
    en: `This table is handmade, so the pattern of copper shavings on the tabletop surface may vary within certain limits. It never repeats and is always unique.`,
    ro: `Această masă este realizată manual, astfel încât modelul de aschii de cupru de pe suprafața blatului poate varia în anumite limite. Nu se repetă niciodată și este întotdeauna unic.`,
    ru: `Это столик создан вручную, поэтому рисунок медной стружки на поверхности столешницы будет отличаться в некоторых пределах. Он никогда не повторяется и  всегда уникален.`,
  },
  {
    vendor_code: "10202-5-c0m0w0h0d0",
    en: `Tabletop made of natural pine solid wood.`,
    ro: `Blatul mesei este realizat din lemn masiv de brad natural.`,
    ru: `Столешница из натурального массива сосны.`,
  },
  {
    vendor_code: "10202-6-c0m0w0h0d0",
    en: `A round extendable table made of tempered glass would look very beautiful in your kitchen or living room.`,
    ro: `O masă rotundă extensibilă din sticlă temperată ar arăta foarte frumos în bucătăria sau sufrageria dvs.`,
    ru: `Круглый раздвижной стол из каленого стекла будет очень красиво смотреться на Вашей кухне или в гостиной.`,
  },
  {
    vendor_code: "10202-7-c0m0w0h0d0",
    en: `An original small table with an unusual design will embellish the interior in the living room, bedroom, or balcony.`,
    ro: `O masă mică originală, cu un design neobișnuit, va îmbogăți interiorul din sufragerie, dormitor sau balcon.`,
    ru: `Оригинальный маленький стол необычного дизайна украсит интерьер в гостиной, в спальне или на балконе.`,
  },
  {
    vendor_code: "10202-8-c0m0w0h0d0",
    en: `The information about the technical specifications, package contents, country of manufacture, appearance, and color of the product is for reference purposes and is c0m0w0h0d0d on the latest available information at the time of publication.`,
    ro: `Informațiile despre specificațiile tehnice, conținutul pachetului, țara de fabricație, aspectul și culoarea produsului sunt cu titlu de referință și se bazează pe cele mai recente informații disponibile la momentul publicării.`,
    ru: `Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях`,
  },
  {
    vendor_code: "10202-9-c0m0w0h0d0",
    en: `A loft-style table is a solution for those who are looking for a versatile table for various tasks.`,
    ro: `O masă în stil loft este o soluție pentru cei care caută o masă versatilă pentru diferite activități.`,
    ru: `Стол в лофт стиле - решение для тех, кто ищет универсальный стол для различных задач.`,
  },
  {
    vendor_code: "10202-10-c0m0w0h0d0",
    en: `One of the versatile and popular types is the rectangular table. Such a piece of furniture will help create coziness, atmosphere, and efficiently utilize the space in the kitchen, even in a small area.`,
    ro: `Unul dintre tipurile versatile și populare este masa dreptunghiulară. Un astfel de obiect de mobilier va ajuta să creați intimitate, atmosferă și să utilizați eficient spațiul în bucătărie, chiar și într-un spațiu mic.`,
    ru: `Один из универсальных и популярных видов является прямоугольный стол. Такой предмет корпусной мебели поможет создать уют, атмосферу, функционально использовать пространство кухни, даже в небольшое пространство.`,
  },
  {
    vendor_code: "10202-11-c0m0w0h0d0",
    en: `A folding rectangular plastic table is an excellent choice if you need a convenient and spacious garden or dining table.`,
    ro: `O masă rectangulară pliabilă din plastic este o alegere excelentă dacă aveți nevoie de o masă comodă și spațioasă pentru grădină sau pentru masă.`,
    ru: `Складной прямоугольный пластиковый стол – отличный выбор, если вам нужен удобный и вместительный садовый или обеденный стол.`,
  },
  {
    vendor_code: "10203-1-c0m0w0h0d0",
    en: "Stool with metal frame – elegant, practical, and very comfortable stool with a soft seat.",
    ro: "Scaun cu cadru metalic – scaun elegant, practic și foarte confortabil, cu un scaun moale.",
    ru: "Табуретки на металлокаркасе – элегантный, практичный и очень комфортный табурет с мягким сидением.",
  },
  {
    vendor_code: "10203-2-c0m0w0h0d0",
    en: "Stool made of natural wood with a hard seat, with three stable legs.",
    ro: "Scaun realizat din lemn natural, cu un scaun dur și cu trei picioare stabile.",
    ru: "Табурет из натурального дерева с жестким сиденьем, с тремя устойчивыми ножками.",
  },
  {
    vendor_code: "10203-3-c0m0w0h0d0",
    en: "Kitchen stool made of wood with a soft seat.",
    ro: "Scaun de bucătărie realizat din lemn, cu un scaun moale.",
    ru: "Табурет для кухни деревянный с мягкой сидушкой.",
  },
  {
    vendor_code: "10203-4-c0m0w0h0d0",
    en: "Wooden chair – a universal interior item that can easily be moved to any room, be it the kitchen, bathroom, nursery, hallway, or balcony.",
    ro: "Scaun din lemn – un articol de interior universal care poate fi mutat cu ușurință în orice încăpere, fie ea bucătăria, baia, camera copiilor, holul sau balconul.",
    ru: "Стул деревянный – универсальный предмет интерьера, легко перенести в любое помещение, будь то кухня, ванная, детская, прихожая или балкон.",
  },
  {
    vendor_code: "10203-5-c0m0w0h0d0",
    en: "Our product guarantees high quality and durability, confirmed by the long-standing reputation of the company.",
    ro: "Produsul nostru garantează calitatea înaltă și durabilitatea, confirmate de reputația îndelungată a companiei.",
    ru: "Наше изделие гарантирует высокое качество и долговечность, подтвержденные многолетней репутацией компании.",
  },
  {
    vendor_code: "10301-1-c0m0w0h0d0",
    en: "Information about technical specifications, delivery set, country of origin, product appearance, and color is for reference only and is based on the latest information available at the time of publication.",
    ro: "Informații despre specificațiile tehnice, setul de livrare, țara de origine, aspectul produsului și culoarea acestuia sunt doar pentru referință și se bazează pe cele mai recente informații disponibile la momentul publicării.",
    ru: "Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях.",
  },
  {
    vendor_code: "10301-2-c0m0w0h0d0",
    en: "Soft and dense velvet combined with sparkling rhinestones - beautiful appearance, wide and cozy seat, comfortable armrests, rocking mechanism, and height adjustment - maximum comfort.",
    ro: "Catifea moale și densă în combinație cu pietrele strălucitoare - aspect frumos, scaun larg și confortabil, cotiere confortabile, mecanism de balansare și ajustare a înălțimii - confort maxim.",
    ru: "Мягкий и плотный велюр в сочетании со сверкающими стразами - прекрасный внешний вид, широкое и уютное сидение, удобные подлокотники, механизм качания и регулировка по высоте - максимальный комфорт.",
  },
  {
    vendor_code: "10301-3-c0m0w0h0d0",
    en: "Ergonomic chair – a base model with a high backrest, combining necessary adjustments, ergonomic shape corresponding to the anatomical shape of a person, modern design, and maximum comfort at an affordable price.",
    ro: "Scaun ergonomic – un model de bază cu un spătar înalt, care combină ajustările necesare, forma ergonomică care corespunde formei anatomice a unei persoane, design modern și confort maxim la un preț accesibil.",
    ru: "Эргономичное кресло – базовая модель с высокой спинкой, сочетающая в себе необходимые настройки, эргономичную форму, соответствующую анатомической форме человека, современный дизайн и максимальный комфорт по доступной цене.",
  },
  {
    vendor_code: "10301-4-c0m0w0h0d0",
    en: "Gaming computer chair has a stylish and practical design, allowing you to comfortably spend time playing games.",
    ro: "Scaunul pentru calculator de gaming are un design elegant și practic, care permite petrecerea confortabilă a timpului în fața jocurilor.",
    ru: "Игровое компьютерное кресло обладает стильным и практичным дизайном, позволяя с комфортом проводить время за играми.",
  },
  {
    vendor_code: "10301-5-c0m0w0h0d0",
    en: "Elegant modern design executive chair.",
    ro: "Scaun executiv cu design modern elegant.",
    ru: "Элегантное кресло руководителя современного дизайна.",
  },
  {
    vendor_code: "10301-6-c0m0w0h0d0",
    en: "Comfortable seat on an ultra-strong steel frame.",
    ro: "Scaun confortabil pe un cadru din oțel ultra-rezistent.",
    ru: "Комфортное сиденье на сверхпрочном стальном каркасе.",
  },
  {
    vendor_code: "10302-1-c0m0w0h0d0",
    en: "Computer table with a hutch, drawers, and shelves - a compact home office solution that organizes your workspace.",
    ro: "Masa de calculator cu hutch, sertare și rafturi - o soluție compactă pentru biroul de acasă, care organizează spațiul de lucru.",
    ru: "Компьютерный стол с надстройкой, ящиками и полками - это компактный домашний офис, который решает проблему организации рабочего пространства.",
  },
  {
    vendor_code: "10302-2-c0m0w0h0d0",
    en: "Gaming computer table - highly stable, practical, and very comfortable gaming table with top-notch gaming features.",
    ro: "Masa de calculator pentru jocuri - foarte stabilă, practică și foarte confortabilă, cu caracteristici de joc de top.",
    ru: "Стол компьютерный геймерский - это высокоустойчивый, практичный и очень комфортный игровой стол с самыми высокими игровыми характеристиками.",
  },
  {
    vendor_code: "10302-3-c0m0w0h0d0",
    en: "Information about technical specifications, delivery set, country of origin, product appearance, and color is for reference only and is based on the latest information available at the time of publication.",
    ro: "Informații despre specificațiile tehnice, setul de livrare, țara de origine, aspectul produsului și culoarea acestuia sunt doar pentru referință și se bazează pe cele mai recente informații disponibile la momentul publicării.",
    ru: "Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях.",
  },
  {
    vendor_code: "10302-4-c0m0w0h0d0",
    en: "Information about technical specifications, delivery set, country of origin, product appearance, and color is for reference only and is based on the latest information available at the time of publication.",
    ro: "Informații despre specificațiile tehnice, setul de livrare, țara de origine, aspectul produsului și culoarea acestuia sunt doar pentru referință și se bazează pe cele mai recente informații disponibile la momentul publicării.",
    ru: "Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях.",
  },
  {
    vendor_code: "10302-5-c0m0w0h0d0",
    en: "Table for setting up a workspace at home and in the office.",
    ro: "Masa pentru amenajarea unui spațiu de lucru acasă și la birou.",
    ru: "Стол для оборудования рабочего пространства в доме и офисе.",
  },
  {
    vendor_code: "10302-6-c0m0w0h0d0",
    en: "Height-adjustable table for both sitting and standing work. Electric drive, reliable motor, smooth adjustment, 2 memory positions, auto-stop – collision protection, button lock to prevent accidental presses. Load capacity up to 50 kg.",
    ro: "Masă reglabilă pe înălțime pentru lucru atât șezând, cât și stând. Mecanism electric, motor fiabil, reglare ușoară, 2 poziții în memorie, protecție anti-coliziune, blocare a butoanelor pentru a preveni apăsările accidentale. Capacitate de încărcare până la 50 kg.",
    ru: "Стол с регулируемой высотой для работы и сидя, и стоя. Электропривод, надёжный мотор, плавная регулировка, 2 положения в памяти, автостоп – защита от столкновений, блокировка кнопок от случайных нажатий. Нагрузка до 50кг.",
  },
  {
    vendor_code: "10303-1-c0m0w0h0d0",
    en: "Information about technical specifications, delivery set, country of origin, product appearance, and color is for reference only and is based on the latest information available at the time of publication.",
    ro: "Informații despre specificațiile tehnice, setul de livrare, țara de origine, aspectul produsului și culoarea acestuia sunt doar pentru referință și se bazează pe cele mai recente informații disponibile la momentul publicării.",
    ru: "Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях.",
  },
  {
    vendor_code: "10303-2-c0m0w0h0d0",
    en: "Chair with black eco-leather easily fits into any interior due to its modern and minimalist design.",
    ro: "Scaun cu piele ecologică neagră care se potrivește ușor în orice interior datorită designului său modern și minimalist.",
    ru: "Кресло с черной экокожей легко вписывается в любой интерьер благодаря своему современному и минималистичному дизайну.",
  },
  {
    vendor_code: "10303-3-c0m0w0h0d0",
    en: "Comfortable, practical, and versatile chair.",
    ro: "Scaun confortabil, practic și versatil.",
    ru: "Удобный, практичный и универсальный стул.",
  },
  {
    vendor_code: "10303-4-c0m0w0h0d0",
    en: "Nylon legs + evacuation function, steel legs + evacuation function, nylon legs, steel legs.",
    ro: "Picioare din nailon + funcție de evacuare, picioare din oțel + funcție de evacuare, picioare din nailon, picioare din oțel.",
    ru: "Нейлоновые ножки + функция эвакуации, стальные ножки + функция эвакуации, нейлоновые ножки, стальные ножки.",
  },
  {
    vendor_code: "10303-5-c0m0w0h0d0",
    en: "Visitor chair in cream color - the epitome of comfort and elegance. It not only adds a unique style to your space but also provides visitors with a high level of comfort.",
    ro: "Scaun pentru vizitatori în culoarea crem - epitomul confortului și eleganței. Acesta nu numai că adaugă un stil unic spațiului dumneavoastră, ci oferă și vizitatorilor un nivel înalt de confort.",
    ru: "Кресло для посетителей в кремовом цвете — это воплощение комфорта и элегантности. Оно не только придаст вашему пространству особый стиль, но и обеспечит посетителям высокий уровень комфорта.",
  },
  {
    vendor_code: "10303-6-c0m0w0h0d0",
    en: "Bright design: Orange eco-leather gives the chair not only a stylish appearance but also provides ease of maintenance and durability.",
    ro: "Design strălucitor: pielea ecologică portocalie oferă scaunului nu doar un aspect elegant, ci și o întreținere ușoară și durabilitate.",
    ru: "Яркий дизайн: Оранжевая экокожа придает креслу не только стильный внешний вид, но и обеспечивает легкость ухода и долговечность.",
  },
  {
    vendor_code: "10401-1-c0m0w0h0d0",
    en: "Wardrobe with sliding doors is made from laminated particle board according to the latest European technologies.",
    ro: "Dulapul cu uși glisante este realizat din PAL laminat conform ultimelor tehnologii europene.",
    ru: "Шкаф купе изготавливается из ЛДСП по новейшим европейским технологиям.",
  },
  {
    vendor_code: "10401-2-c0m0w0h0d0",
    en: "Opening of drawers and central doors occurs through the space between the plank and the front.",
    ro: "Deschiderea sertarelor și a ușilor centrale se face prin spațiul dintre plancă și front.",
    ru: "Открывания выдвижных ящиков и центральных дверей происходит за счет пространства между планкой и фасадом.",
  },
  {
    vendor_code: "10401-3-c0m0w0h0d0",
    en: "Information about technical specifications, delivery set, country of origin, product appearance, and color is for reference only and is based on the latest information available at the time of publication.",
    ro: "Informații despre specificațiile tehnice, setul de livrare, țara de origine, aspectul produsului și culoarea acestuia sunt doar pentru referință și se bazează pe cele mai recente informații disponibile la momentul publicării.",
    ru: "Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях.",
  },
  {
    vendor_code: "10401-4-c0m0w0h0d0",
    en: "Two-door wardrobe with drawers – an excellent option for a small modern apartment or country house. This versatile model will look appropriate in the hallway, bedroom, living room, nursery, dressing room, and even office space.",
    ro: "Dulap cu două uși și sertare – o opțiune excelentă pentru un apartament modern mic sau o casă de țară. Această modelă versatilă se va potrivi în hol, dormitor, living, cameră pentru copii, dressing și chiar spațiu de birou.",
    ru: "Двухстворчатый шкаф с ящиками – отличный вариант для небольшой современной квартиры или загородного дома. Эта универсальная модель будет уместно смотреться в прихожей, спальне, гостиной, детской комнате, гардеробе и даже офисном помещении.",
  },
  {
    vendor_code: "10401-5-c0m0w0h0d0",
    en: "Hanging cabinet will undoubtedly decorate your home, apartment, or office.",
    ro: "Dulapul suspendat va decora cu siguranță casa, apartamentul sau biroul dumneavoastră.",
    ru: "Шкаф-пенал навесной несомненно украсит Ваш дом, квартиру или офис.",
  },
  {
    vendor_code: "10402-1-c0m0w0h0d0",
    en: "Stockholm chest of drawers with doors will become a stylish part of the interior in a modern apartment in Scandinavian or loft style.",
    ro: "Comoda Stockholm cu uși va deveni o parte stilată a interiorului într-un apartament modern în stil scandinav sau loft.",
    ru: "Комод с дверцами Стокгольм станет стильной частью интерьера в современной квартире в скандинавском стиле или лофт.",
  },
  {
    vendor_code: "10402-2-c0m0w0h0d0",
    en: "Spacious and functional chest of drawers with four central pull-out drawers creates a cozy atmosphere in the living room or bedroom.",
    ro: "Comodă spațioasă și funcțională cu patru sertare retractabile centrale creează o atmosferă confortabilă în living sau dormitor.",
    ru: "Вместительный и функциональный комод с четырьмя выдвижными ящиками по центру создаст уютную атмосферу в интерьере гостиной или спальни.",
  },
  {
    vendor_code: "10402-3-c0m0w0h0d0",
    en: "Tall chest of drawers with 4 pull-out drawers - suitable for the nursery, living room, and other rooms in the house.",
    ro: "Comodă înaltă cu 4 sertare retractabile - potrivită pentru camera copiilor, living și alte camere din casă.",
    ru: "Высокий комод на 4 выдвижных ящика - для детской, гостиной и остальных комнат в доме.",
  },
  {
    vendor_code: "10402-4-c0m0w0h0d0",
    en: "Universal, compact, but roomy white wooden chest of drawers in a loft style with 4 drawers fits perfectly into any interior of an apartment, house, cottage, or office.",
    ro: "Comodă din lemn alb universală, compactă, dar spațioasă, în stil loft, cu 4 sertare, se potrivește perfect în orice interior al unui apartament, casă, vilă sau birou.",
    ru: "Универсальный, компактный, но вместительный белый деревянный комод тумба с 4 ящиками в стиле лофт, прекрасно впишется в любой интерьер квартиры, дома, дачи или офиса.",
  },
  {
    vendor_code: "10402-5-c0m0w0h0d0",
    en: "Introducing you to an elegant and functional white chest of drawers with drawers that will be the perfect addition to any interior.",
    ro: "Vă prezentăm un elegant și funcțional cufăr alb cu sertare, care va fi o completare perfectă pentru orice interior.",
    ru: "Представляем вам элегантный и функциональный комод белый с ящиками, который станет идеальным дополнением для любого интерьера.",
  },
  {
    vendor_code: "10403-1-c0m0w0h0d0",
    en: "Upholstered bedside table is made of velvet, equipped with two drawers with hidden mounting guides with closers.",
    ro: "Masa de noptieră tapițată este realizată din catifea și este echipată cu două sertare cu ghidaje de montare ascunse și închizătoare.",
    ru: "Тумба прикроватная с мягкой обивкой выполнена из велюра оснащена двумя ящиками с направляющими скрытого монтажа с доводчиком.",
  },
  {
    vendor_code: "10403-2-c0m0w0h0d0",
    en: "The Scandinavian-style nightstand design fits perfectly into any interior and any room in your home.",
    ro: "Designul noptierei în stil scandinav se potrivește perfect în orice interior și orice cameră din casa dumneavoastră.",
    ru: "Дизайн тумбы в скандинавском стиле отлично впишется в любой интерьер и любое помещение вашем доме.",
  },
  {
    vendor_code: "10403-3-c0m0w0h0d0",
    en: "This nightstand will fit perfectly into any room - whether it's the living room, bedroom, nursery, or even the hallway or corridor.",
    ro: "Această noptieră se va potrivi perfect în orice cameră - fie că este livingul, dormitorul, camera copiilor sau chiar holul sau coridorul.",
    ru: "Эта тумба прекрасно впишется в любую комнату – будь то гостиная, спальня, детская или даже прихожая или коридор.",
  },
  {
    vendor_code: "10403-4-c0m0w0h0d0",
    en: "Loft-style bedside table with a rectangular tabletop and black matte metal legs for your interior.",
    ro: "Noptiere în stil loft cu blat dreptunghiular și picioare metalice negre mate pentru interiorul dvs.",
    ru: "Прикроватная тумбочка в стиле лофт с прямоугольной столешницей и металлическими ножками черного матового цвета для вашего интерьера.",
  },
  {
    vendor_code: "10403-5-c0m0w0h0d0",
    en: "Bedside table is a classic option for a bedroom or living room.",
    ro: "Noptiere este o opțiune clasică pentru dormitor sau living.",
    ru: "Тумба прикроватная – это классический вариант мебели для спальни или гостиной.",
  },
  {
    vendor_code: "10501-1-c0m0w0h0d0",
    en: "Floor-standing coat rack for clothes, made of metal, 151 cm high. Thanks to this height, the rack can hold long clothes: dresses, coats, fur coats.",
    ro: "Cuier pentru haine, realizat din metal, cu o înălțime de 151 cm. Datorită acestei înălțimi, suportul poate ține haine lungi: rochii, paltoane, haine de blană.",
    ru: "Вешалка напольная для одежды металлическая высотой 151 см. Благодаря такой высоте на вешалке можно поместить длинную одежду: платья, пальто, шубу.",
  },
  {
    vendor_code: "10501-2-c0m0w0h0d0",
    en: "Stylish and compact coat rack will quickly organize the hallway. The rack assembles quickly, is stable and durable. Additionally, hooks for bags and accessories and a shoe shelf are provided.",
    ro: "Cuierul elegant și compact va organiza rapid holul. Cuierul se asamblează rapid, este stabil și durabil. În plus, sunt prevăzute cârlige pentru genți și accesorii și o etajeră pentru încălțăminte.",
    ru: "Стильная и компактная вешалка для одежды позволит быстро навести порядок в прихожей. Вешалка быстро собирается, устойчивая и прочная. Дополнительно предусмотрены крючки для сумок и аксессуаров и полка для обуви.",
  },
  {
    vendor_code: "10501-3-c0m0w0h0d0",
    en: "Floor-standing coat rack-stand, 12 hooks made of metal pipe with a diameter of 32 mm, on which twelve hooks are located.",
    ro: "Cuier de podea cu 12 cârlige, realizat din țeavă metalică cu diametrul de 32 mm, pe care sunt dispuse douăsprezece cârlige.",
    ru: "Напольная вешалка-стойка, 12 крючков изготовлена из металлической трубы диаметром 32 мм, на которой расположены двенадцать крючков.",
  },
  {
    vendor_code: "10502-1-c0m0w0h0d0",
    en: "Shoe rack harmoniously fits into the interior of the hallway, apartment, house, cottage.",
    ro: "Raftul pentru pantofi se potrivește armonios în interiorul holului, apartamentului, casei, cabanei.",
    ru: "Этажерка для обуви гармонично вписывается в интерьер прихожей, квартиры, дома, дачи.",
  },
  {
    vendor_code: "10502-2-c0m0w0h0d0",
    en: "Narrow metal shoe rack for organizing shoe storage.",
    ro: "Raft îngust pentru pantofi din metal pentru organizarea depozitării pantofilor.",
    ru: "Обувница узкая металлическая для организации хранения обуви.",
  },
  {
    vendor_code: "10502-3-c0m0w0h0d0",
    en: "Information about technical specifications, delivery set, country of origin, product appearance, and color is for reference only and is based on the latest information available at the time of publication.",
    ro: "Informații despre specificațiile tehnice, setul de livrare, țara de origine, aspectul produsului și culoarea acestuia sunt doar pentru referință și se bazează pe cele mai recente informații disponibile la momentul publicării.",
    ru: "Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях.",
  },
  {
    vendor_code: "10502-4-c0m0w0h0d0",
    en: "Compact metal shelving for storing things is made of stainless steel and coated with anti-corrosion spraying.",
    ro: "Raft compact din metal pentru depozitarea lucrurilor este realizat din oțel inoxidabil și acoperit cu un strat anti-coroziv.",
    ru: "Компактная металлическая полка для хранения вещей сделана из нержавеющей стали и покрыта антикоррозийным напылением.",
  },
]
