import { ItemsDescription } from "../schema"

export const itemsDescriptionArr: ItemsDescription[] = [
  {
    vendor_code: "10101--1--base",
    en: `The sofa can be comfortably slept on without disassembling it. In its unfolded state, the sofa forms a spacious sleeping area. The sofa is equipped with a storage box for bedding.`,
    ro: `Pe canapea se poate dormi confortabil fără să o desfășurați. În forma sa desfășurată, canapeaua formează un spațiu generos pentru dormit. Canapeaua este echipată cu o cutie de depozitare pentru lenjerie de pat.`,
    ru: `На диване можно комфортно спать, не разбирая его. В разложенном виде диван образует просторное спальное место. Диван оснащен бельевым коробом.`,
  },
  {
    vendor_code: "10101--2--base",
    en: `You can always put your phone on the armrest tabletop and place a cup of tea there. In its unfolded state, the sofa forms a spacious sleeping area. The sofa is equipped with a storage box for bedding.`,
    ro: `Întotdeauna puteți pune telefonul pe blatul de la cotieră și puteți pune o ceașcă de ceai acolo. În forma sa desfășurată, canapeaua formează un spațiu generos pentru dormit. Canapeaua este echipată cu o cutie de depozitare pentru lenjerie de pat.`,
    ru: `На столешницу подлокотника всегда можно положить телефон и поставить чашечку чая. В разложенном виде диван образует просторное спальное место. Диван оснащен бельевым коробом.`,
  },
  {
    vendor_code: "10101--3--base",
    en: `The sofa will fit seamlessly into the interior of a modern urban apartment. Thanks to its compact size, it will also make an excellent addition to a child's room or kitchen.`,
    ro: `Canapeaua se va integra perfect în interiorul unui apartament urban modern. Datorită dimensiunilor sale compacte, va fi de asemenea un excelent adaos pentru camera unui copil sau pentru bucătărie.`,
    ru: `Диван удачно впишется в обстановку современной городской квартиры. Благодаря компактным размерам он также станет отличным дополнением детской комнаты или кухни`,
  },
  {
    vendor_code: "10101--4--base",
    en: `The sofa section allows you to take a semi-reclining position on the couch. Beneath this section, there is a spacious storage box for linens. When unfolded, the sofa forms a generous sleeping area.`,
    ro: `Secțiunea de canapea vă permite să adoptați o poziție semireclinată pe canapea. Sub această secțiune, se află o cutie spațioasă pentru lenjerie. Când este desfăcut, canapeaua devine un spațiu generos pentru dormit.`,
    ru: `Секция канапе позволяет принять на диване положение полулежа. Под данной секцией расположен вместительный бельевой короб. В разложенном виде диван образует просторное спальное место.`,
  },
  {
    vendor_code: "10101--5--base",
    en: `The information about the technical specifications, package contents, country of manufacture, appearance, and color of the product is for reference purposes and is based on the latest available information at the time of publication.`,
    ro: `Informațiile despre specificațiile tehnice, conținutul pachetului, țara de fabricație, aspectul și culoarea produsului sunt cu titlu de referință și se bazează pe cele mai recente informații disponibile la momentul publicării.`,
    ru: `Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях`,
  },
  {
    vendor_code: "10101--6--base",
    en: `The model's advantage lies in its original design in the spirit of the latest European trends, making it harmoniously blend into any interior. The flock upholstery is low-maintenance, pleasant to the touch, and durable.`,
    ro: `Avantajul modelului este designul original în spiritul ultimelor tendințe europene, deci arată armonios în orice interior. Tapițeria de turmă este nemaipomenită în îngrijire, plăcută la atingere și rezistentă la uzură.`,
    ru: `Достоинство модели — оригинальный дизайн в духе последних европейских трендов, поэтому она гармонично выглядит в любом интерьере. Обивка флок неприхотлива в уходе, приятна на ощупь и износоустойчива.`,
  },
  {
    vendor_code: "10101--7--base",
    en: `The model has a sturdy frame designed for intense daily loads, a safe filler that easily restores its shape, and unpretentious upholstery.`,
    ro: `Modelul are un cadru robust conceput pentru sarcini zilnice intense, o umplutură sigură care își restabilește cu ușurință forma și o tapițerie nepretențioasă.`,
    ru: `У модели прочный каркас, рассчитанный на интенсивные ежедневные нагрузки, безопасный наполнитель, легко восстанавливающий форму, и неприхотливая в уходе обивка`,
  },
  {
    vendor_code: "10101--8--base",
    en: `This model can be placed along any wall or in the center - it all depends on the concept of the interior.`,
    ro: `Acest model poate fi plasat de-a lungul oricărui perete sau în centru - totul depinde de conceptul interiorului.`,
    ru: `Данную модель можно поставить как вдоль любой стены, так и по центру — все зависит от концепции интерьера.`,
  },
  {
    vendor_code: "10101--9--base",
    en: `The straight sofa will be the perfect solution for arranging waiting areas, reception areas, or workspaces. Your guests and employees will appreciate the comfort and style of this wonderful piece of furniture.`,
    ro: `Canapeaua dreaptă va fi soluția perfectă pentru amenajarea zonelor de așteptare, a zonelor de primire sau a spațiilor de lucru. Oaspeții și angajații dvs. vor aprecia confortul și stilul acestui minunat obiect de mobilier.`,
    ru: `Прямой диван станет идеальным решением для обустройства зоны ожидания, приемной или рабочего пространства. Ваши гости и сотрудники оценят комфорт и стиль этого замечательного предмета мебели.`,
  },
  {
    vendor_code: "10101--10--base",
    en: `The Olympus sofa is a popular classic model with optimal dimensions, which makes it look great even in a small space. It can be placed along any wall or in the center, depending on the interior concept.`,
    ro: `Canapeaua Olympus este un model clasic popular, cu dimensiuni optime, ceea ce o face să arate excelent chiar și într-un spațiu mic. Poate fi plasată de-a lungul oricărei pereți sau în centrul încăperii, în funcție de conceptul interior.`,
    ru: `Диван Олимп — популярная классическая модель с оптимальными габаритами, благодаря которым отлично смотрится даже в небольшом помещении. Ее можно поставить как вдоль любой стены, так и по центру — все зависит от концепции интерьера.`,
  },
  {
    vendor_code: "10101--11--base",
    en: `The model features a sturdy frame designed for intensive daily use, safe filler that easily regains its shape, and low-maintenance upholstery.`,
    ro: `Modelul prezintă un cadru rezistent conceput pentru utilizare intensivă zilnică, umplutură sigură ce își redobândește ușor forma și tapițerie ușor de întreținut.`,
    ru: `У модели прочный каркас , рассчитанный на интенсивные ежедневные нагрузки, безопасный наполнитель, легко восстанавливающий форму, и неприхотливая в уходе обивка.`,
  },
  {
    vendor_code: "10101--12--base",
    en: `The "Comfort" sofa is a modern solution with an optimal balance of cost and quality. The model features a sturdy frame designed for intensive daily use, safe filler that easily regains its shape, and low-maintenance upholstery.`,
    ro: `Canapeaua "Comfort" reprezintă o soluție modernă cu un echilibru optim între cost și calitate. Modelul dispune de un cadru solid, proiectat pentru utilizare intensivă zilnică, umplutură sigură care își recâștigă ușor forma și tapițerie ușor de întreținut.`,
    ru: `Диван "Комфорт"  — современное решение с оптимальным соотношением стоимости и качества. У модели прочный каркас, рассчитанный на интенсивные ежедневные нагрузки, безопасный наполнитель, легко восстанавливающий форму, и неприхотливая в уходе обивка.`,
  },
  {
    vendor_code: "10102--1--base",
    en: `The base of the chair is a metal frame with orthopedic slats. Thanks to the sturdy metal frame, the chair can withstand loads up to 200 kg. Flexible wooden slats provide good air circulation and a springy effect.`,
    ro: `Baza scaunului este un cadru metalic cu lamele ortopedice. Datorită cadrului metalic rezistent, scaunul poate suporta încărcături de până la 200 kg. Lamele de lemn flexibile asigură o bună circulație a aerului și un efect elastic.`,
    ru: `Основа кресла — металлокаркас с ортопедическими ламелями. Благодаря прочному металлическому каркасу кресло выдерживает нагрузку до 200 кг. Гибкие деревянные ламели обеспечивают хорошую циркуляцию воздуха и пружинящий эффект.`,
  },
  {
    vendor_code: "10102--2--base",
    en: `The cozy armchair on legs "Fantazer" will fit perfectly into any modern home or office interior.`,
    ro: `Fotoliul confortabil pe picioare "Fantazer" se va integra perfect în orice interior modern de acasă sau de birou.`,
    ru: `Уютное интерьерное кресло на ножках Фантазер прекрасно впишется в любой современный домашний или офисный интерьер.`,
  },
  {
    vendor_code: "10102--3--base",
    en: `The color of the upholstery depends on the batch of fabric and can vary from delicate to saturated.`,
    ro: `Culoarea tapiteriei depinde de lotul de material textil și poate varia de la delicată la saturată.`,
    ru: `Цвет обивки зависит от партии ткани и может варьироваться от нежного до насыщенного.`,
  },
  {
    vendor_code: "10102--4--base",
    en: `It will be perfect for any office or will adorn the interior of your living room, bedroom, study, or any room, providing comfort and coziness in your home.`,
    ro: `Va fi perfect pentru orice birou sau va împodobi interiorul livingului, dormitorului, biroului, sau oricărei încăperi, oferind confort și intimitate în casa dvs.`,
    ru: `Идеально подойдет для любого офиса или украсит интерьер Вашей гостиной, спальни, комнаты, кабинета, обеспечит комфорт и уют в Вашем доме.`,
  },
  {
    vendor_code: "10102--5--base",
    en: `The unique armchair with a backrest will instantly transform your interior and provide 100% comfort.`,
    ro: `Fotoliul unic cu spătarul va transforma instantaneu interiorul dumneavoastră și va oferi 100% confort`,
    ru: `Уникальное кресло со спинкой моментально преобразит ваш интерьер и обеспечит 100% комфорт.`,
  },
  {
    vendor_code: "10102--6--base",
    en: `The straight office chair is compact and small in size, making it a versatile solution for various spaces.`,
    ro: `Scaunul de birou drept este compact și de dimensiuni mici, ceea ce-l face o soluție versatilă pentru diferite spații.`,
    ru: `Кресло прямое офисное – компактное и малогабаритное, что делает его универсальным решением для разных помещений.`,
  },
  {
    vendor_code: "10102--7--base",
    en: `This model looks luxurious, withstands heavy loads without compressing the filler and deforming the frame.`,
    ro: `Această model arată luxos, rezistă la încărcături mari fără a comprima umplutura și a deforma cadru.`,
    ru: `Данная модель роскошно выглядит, выдерживает большие нагрузки без продавливания наполнителя и деформации каркаса. `,
  },
  {
    vendor_code: "10102--8--base",
    en: `The cover is made of cotton and polyester with added viscose and linen. It's a durable and comfortable cover with a simple pattern.`,
    ro: `Husa este fabricată din bumbac și poliester cu adaos de viscoză și in. Este o husă durabilă și confortabilă, cu un model simplu.`,
    ru: `Чехол изготовлен из хлопка и полиэстера с добавлением вискозы и льна. Прочный и комфортный чехол с простым рисунком.`,
  },
  {
    vendor_code: "10102--9--base",
    en: `This is safe furniture for a child's room and comfortable furniture for an adult's room, as the armchair does not have sharp corners.`,
    ro: `Aceasta este o mobilă sigură pentru camera copilului și mobilă confortabilă pentru camera unui adult, deoarece fotoliul nu are colțuri ascuțite.`,
    ru: `Это безопасная мебель в детскую комнату и комфортная мебель для комнаты взрослых, так как кресло не имеет острых углов.`,
  },
  {
    vendor_code: "10201--1--base",
    en: `An elegant fusion of classic and modern design with a curved backrest that combines the functions of both a backrest and armrest.`,
    ro: `Un echilibru elegant între clasic și modern, cu un spătar încovoiat care îmbină funcțiile de spătar și suport pentru brațe.`,
    ru: `Элегантный симбиоз классики и современности с изогнутой спинкой, совмещающей в себе функции подлокотника.`,
  },
  {
    vendor_code: "10201--2--base",
    en: `During the chair's production, the most environmentally friendly and durable material for furniture manufacturing was used – solid pine wood, which looks even better over time.`,
    ro: `În timpul producției scaunului, s-a folosit cel mai prietenos și durabil material pentru fabricarea mobilei - lemnul masiv de pin, care arată și mai bine în timp.`,
    ru: `При производстве стула использован наиболее экологичный и прочный материал для производства мебели – массив сосны, который со временем выглядит только лучше.`,
  },
  {
    vendor_code: "10201--3--base",
    en: `This comfortable chair with soft seat and backrest will be a great addition to any room in your home.`,
    ro: `Acest scaun confortabil cu șezut și spătar moale va fi o excelentă completare pentru orice cameră din casa dvs.`,
    ru: `Этот комфортный стул с мягкими сиденьем и спинкой станет отличным дополнением для любой комнаты вашего дома. `,
  },
  {
    vendor_code: "10201--4--base",
    en: `The rounded slightly concave backrest is an unusual solution that not only gives the chair a designer look but also creates an optimally comfortable position for your back.`,
    ro: `Spătarul rotunjit ușor concav este o soluție neobișnuită care nu numai că conferă scaunului un aspect de designer, dar creează și o poziție optim de confortabilă pentru spatele dumneavoastră.`,
    ru: `Округлая чуть вогнутая спинка - необычное решение, которое не только придает стулу дизайнерский вид, но и создает оптимально комфортное положение для Вашей спины.`,
  },
  {
    vendor_code: "10201--5--base",
    en: `The seat is of a curved shape, soft, with a soft backrest. The base is made of sturdy metal. There is a swivel mechanism.`,
    ro: `Scaunul are un șezut de formă curbată, moale, cu un spătar moale. Baza este realizată din metal rezistent. Există un mecanism de rotire.`,
    ru: `Сиденье фигурной формы, мягкое, с мягкой спинкой. Основание сделано из прочного металла. Есть механизм вращения.`,
  },
  {
    vendor_code: "10201--6--base",
    en: `The chair is made of durable metal, ensuring its longevity and reliability.`,
    ro: `Scaunul este fabricat din metal rezistent, asigurându-i longevitatea și fiabilitatea.`,
    ru: `Стул изготовлен из прочного металла, что гарантирует его долговечность и надежность.`,
  },
  {
    vendor_code: "10201--7--base",
    en: `Milana chairs are made of multi-layered plywood and a solid steel frame.`,
    ro: `Scaunele Milana sunt fabricate din furnir multistrat și un cadru integral din oțel.`,
    ru: `Стулья Милана изготовлены из многослойной фанеры и стального цельнометаллического каркаса.`,
  },
  {
    vendor_code: "10201--8--base",
    en: `Stylish appearance combined with practical function.`,
    ro: `Aspect elegant combinat cu funcție practică.`,
    ru: `Стильный внешний вид в сочетании с практичной функцией.`,
  },
  {
    vendor_code: "10201--9--base",
    en: `This exquisite pink chair is made of high-quality velvet material, which gives it an elegant and luxurious appearance.`,
    ro: `Acest scaun roz exquisit este fabricat din material de catifea de înaltă calitate, ceea ce îi conferă un aspect elegant și luxos.`,
    ru: `Этот восхитительный розовый стул выполнен из высококачественного бархатного материала, который придает ему элегантный и роскошный вид.`,
  },
  {
    vendor_code: "10201--10--",
    en: `The information about the technical specifications, package contents, country of manufacture, appearance, and color of the product is for reference purposes and is based on the latest available information at the time of publication.`,
    ro: `Informațiile despre specificațiile tehnice, conținutul pachetului, țara de fabricație, aspectul și culoarea produsului sunt cu titlu de referință și se bazează pe cele mai recente informații disponibile la momentul publicării.`,
    ru: `Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях`,
  },
  {
    vendor_code: "10202--1--base",
    en: `The table is equipped with a gas lift swivel mechanism.`,
    ro: `Masa este echipată cu un mecanism de ridicare cu gaz și pivotare.`,
    ru: `Стол снабжен поворотно-подъемным механизмом газ-лифт.`,
  },
  {
    vendor_code: "10202--2--base",
    en: `Multifunctional – can be used as a coffee table or bedside table. Compact – doesn't take up much space, perfect for small-sized apartments. Stylish – white color, original design, round tabletop.`,
    ro: `Multifuncțional - poate fi folosit ca masă de cafea sau masă de noapte. Compact - nu ocupă mult spațiu, perfect pentru apartamentele mici ca suprafață. Elegant - culoare albă, design original, blat de masă rotund.`,
    ru: `Многофункциональный – может использоваться как журнальный или прикроватный. Компактный – не занимает много места, идеальный выбор для небольших по площади квартир. Стильный – белый цвет, оригинальный дизайн, круглая столешница.`,
  },
  {
    vendor_code: "10202--3--base",
    en: `Kitchen table with high-quality tempered glass coating, practical, durable, heavy.`,
    ro: `Masă de bucătărie cu acoperire din sticlă temperată de înaltă calitate, practică, durabilă, grea.`,
    ru: `Стол кухонный с покрытием из закалённого стекла отличного качества, практичный, устойчивый, тяжелый.`,
  },
  {
    vendor_code: "10202--4--base",
    en: `This table is handmade, so the pattern of copper shavings on the tabletop surface may vary within certain limits. It never repeats and is always unique.`,
    ro: `Această masă este realizată manual, astfel încât modelul de aschii de cupru de pe suprafața blatului poate varia în anumite limite. Nu se repetă niciodată și este întotdeauna unic.`,
    ru: `Это столик создан вручную, поэтому рисунок медной стружки на поверхности столешницы будет отличаться в некоторых пределах. Он никогда не повторяется и  всегда уникален.`,
  },
  {
    vendor_code: "10202--5--base",
    en: `Tabletop made of natural pine solid wood.`,
    ro: `Blatul mesei este realizat din lemn masiv de brad natural.`,
    ru: `Столешница из натурального массива сосны.`,
  },
  {
    vendor_code: "10202--6--base",
    en: `A round extendable table made of tempered glass would look very beautiful in your kitchen or living room.`,
    ro: `O masă rotundă extensibilă din sticlă temperată ar arăta foarte frumos în bucătăria sau sufrageria dvs.`,
    ru: `Круглый раздвижной стол из каленого стекла будет очень красиво смотреться на Вашей кухне или в гостиной.`,
  },
  {
    vendor_code: "10202--7--base",
    en: `An original small table with an unusual design will embellish the interior in the living room, bedroom, or balcony.`,
    ro: `O masă mică originală, cu un design neobișnuit, va îmbogăți interiorul din sufragerie, dormitor sau balcon.`,
    ru: `Оригинальный маленький стол необычного дизайна украсит интерьер в гостиной, в спальне или на балконе.`,
  },
  {
    vendor_code: "10202--8--base",
    en: `The information about the technical specifications, package contents, country of manufacture, appearance, and color of the product is for reference purposes and is based on the latest available information at the time of publication.`,
    ro: `Informațiile despre specificațiile tehnice, conținutul pachetului, țara de fabricație, aspectul și culoarea produsului sunt cu titlu de referință și se bazează pe cele mai recente informații disponibile la momentul publicării.`,
    ru: `Информация о технических характеристиках, комплекте поставки, стране изготовления, внешнем виде и цвете товара носит справочный характер и основывается на последних доступных к моменту публикации сведениях`,
  },
  {
    vendor_code: "10202--9--base",
    en: `A loft-style table is a solution for those who are looking for a versatile table for various tasks.`,
    ro: `O masă în stil loft este o soluție pentru cei care caută o masă versatilă pentru diferite activități.`,
    ru: `Стол в лофт стиле - решение для тех, кто ищет универсальный стол для различных задач.`,
  },
  {
    vendor_code: "10202--10--base",
    en: `One of the versatile and popular types is the rectangular table. Such a piece of furniture will help create coziness, atmosphere, and efficiently utilize the space in the kitchen, even in a small area.`,
    ro: `Unul dintre tipurile versatile și populare este masa dreptunghiulară. Un astfel de obiect de mobilier va ajuta să creați intimitate, atmosferă și să utilizați eficient spațiul în bucătărie, chiar și într-un spațiu mic.`,
    ru: `Один из универсальных и популярных видов является прямоугольный стол. Такой предмет корпусной мебели поможет создать уют, атмосферу, функционально использовать пространство кухни, даже в небольшое пространство.`,
  },
  {
    vendor_code: "10202--11--base",
    en: `A folding rectangular plastic table is an excellent choice if you need a convenient and spacious garden or dining table.`,
    ro: `O masă rectangulară pliabilă din plastic este o alegere excelentă dacă aveți nevoie de o masă comodă și spațioasă pentru grădină sau pentru masă.`,
    ru: `Складной прямоугольный пластиковый стол – отличный выбор, если вам нужен удобный и вместительный садовый или обеденный стол.`,
  },
]
