import { ItemsName } from "../schema"
import { itemsArr } from "./items"

const itemsNameBasis: ItemsName[] = [
  {
    vendor_code: "10101-1",
    en: "Straight Sofa Bed FAMILY 1",
    ro: "Canapea extensibilă dreaptă FAMILY 1",
    ru: "Диван-кровать прямой FAMILY 1",
  },
  {
    vendor_code: "10101-2",
    en: "Straight Sofa Bed FAMILY 2",
    ro: "Canapea extensibilă dreaptă FAMILY 2",
    ru: "Диван-кровать прямой FAMILY 2",
  },
  {
    vendor_code: "10101-3",
    en: "Straight Sofa Bed FAMILY 3",
    ro: "Canapea extensibilă dreaptă FAMILY 3",
    ru: "Диван-кровать прямой FAMILY 3",
  },
  {
    vendor_code: "10101-4",
    en: "Straight Sofa Bed FAMILY 4",
    ro: "Canapea extensibilă dreaptă FAMILY 4",
    ru: "Диван-кровать прямой FAMILY 4",
  },
  {
    vendor_code: "10101-5",
    en: "Sofa Bed Karina 1",
    ro: "Canapea Karina 1",
    ru: "Диван-кровать Карина 1",
  },
  {
    vendor_code: "10101-6",
    en: "Straight Sofa Bed Baron 4",
    ro: "Canapea extensibilă dreaptă Baron 4",
    ru: "Диван-кровать прямой Baron 4",
  },
  {
    vendor_code: "10101-7",
    en: "Straight sofa Combo 1",
    ro: "Canapea dreaptă Combo 1",
    ru: "Прямой диван Комби 1",
  },
  {
    vendor_code: "10101-8",
    en: "Sofa Olimp 1",
    ro: "Canapea Olimp 1",
    ru: "Диван-кровать Олимп 1",
  },
  {
    vendor_code: "10101-9",
    en: "Straight sofa Moon 1",
    ro: "Canapea dreaptă Moon 1",
    ru: "Прямой диван Moon 1",
  },
  {
    vendor_code: "10101-10",
    en: "Sofa Olimp 2",
    ro: "Canapea Olimp 2",
    ru: "Диван-кровать Олимп 2",
  },
  {
    vendor_code: "10101-11",
    en: "Futon Couch 1",
    ro: "Canapea extensibilă 1",
    ru: "Диван-книжка 1",
  },
  {
    vendor_code: "10101-12",
    en: "Straight Sofa Comfort 1",
    ro: "Canapea dreaptă Comfort 1",
    ru: "Прямой диван Комфорт 1",
  },
  {
    vendor_code: "10102-1",
    en: "Chair-bed Acrobat Lux 1",
    ro: "Scaun-pat Acrobat Lux 1",
    ru: "Кресло-кровать Акробат Люкс 1",
  },
  {
    vendor_code: "10102-2",
    en: "Soft Armchair Fantasizer 1",
    ro: "Fotoliu moale Fantazator 1",
    ru: "Кресло мягкое Фантазёр 1",
  },
  {
    vendor_code: "10102-3",
    en: "Folding Chair Munich 1",
    ro: "Scaun pliabil München 1",
    ru: "Кресло раскладное Мюнхен 1",
  },
  {
    vendor_code: "10102-4",
    en: "Loft Armchair 1",
    ro: "Fotoliu Loft 1",
    ru: "Кресло Лофт 1",
  },
  {
    vendor_code: "10102-5",
    en: "Dallas Armchair 1",
    ro: "Fotoliu Dallas 1",
    ru: "Кресло Далас 1",
  },
  {
    vendor_code: "10102-6",
    en: "Pause Soft Armchair 1",
    ro: "Fotoliu moale Pauză 1",
    ru: "Кресло мягкое Пауза 1",
  },
  {
    vendor_code: "10102-7",
    en: "Amsterdam Armchair 1",
    ro: "Fotoliu Amsterdam 1",
    ru: "Кресло Амстердам 1",
  },
  {
    vendor_code: "10102-8",
    en: "POANG chair 1",
    ro: "Fotoliul POANG 1",
    ru: "Кресло POANG 1",
  },
  {
    vendor_code: "10102-9",
    en: "Levita Soft Armchair 1",
    ro: "Fotoliu moale Levita 1",
    ru: "Кресло мягкое Левита 1",
  },
  {
    vendor_code: "10201-1",
    en: "Kay Chair 1",
    ro: "Scaun Kay 1",
    ru: "Стул Kay 1",
  },
  {
    vendor_code: "10201-2",
    en: "Ingolt Chair 1",
    ro: "Scaun Ingolt 1",
    ru: "Стул Ингольт 1",
  },
  {
    vendor_code: "10201-3",
    en: "Scaun quiz 1",
    ro: "Quiz chair 1",
    ru: "Стул квиз 1",
  },
  {
    vendor_code: "10201-4",
    en: "Evelina Chair 1",
    ro: "Scaunul Evelina 1",
    ru: "Стул ЭВЕЛИНА 1",
  },
  {
    vendor_code: "10201-5",
    en: "DOBRIN BARNY Bar Stool 1",
    ro: "Scaun de bar DOBRIN BARNY 1",
    ru: "Стул барный DOBRIN BARNY 1",
  },
  {
    vendor_code: "10201-6",
    en: "Soft Armchair HESBY 1",
    ro: "Scaun fotoliu moale HESBY 1",
    ru: "Мягкий стул-кресло HESBY 1",
  },
  {
    vendor_code: "10201-7",
    en: "Milana 1 Chai",
    ro: "Scaun Milana 1",
    ru: "Стул Милана 1",
  },
  {
    vendor_code: "10201-8",
    en: "Kitchen Chair 1",
    ro: "Scaun pentru bucătărie 1",
    ru: "Стул для кухни 1",
  },
  {
    vendor_code: "10201-9",
    en: "Stefano Designer Armchair 1",
    ro: "Fotoliu designer Stefano 1",
    ru: "Стул-кресло дизайнерский Стефано 1",
  },
  {
    vendor_code: "10201-10",
    en: "Kitchen Chair 2",
    ro: "Scaun pentru bucătărie 2",
    ru: "Стул для кухни 2",
  },
  {
    vendor_code: "10202-1",
    en: "Bar table 1",
    ro: "Bar de masă 1",
    ru: "Барный стол 1",
  },
  {
    vendor_code: "10202-2",
    en: "Coffee table 1",
    ro: "Masă de cafea 1",
    ru: "Журнальный стол 1",
  },
  {
    vendor_code: "10202-3",
    en: "Dining table 1",
    ro: "Masă de cină 1",
    ru: "Стол обеденный 1",
  },
  {
    vendor_code: "10202-4",
    en: "Coffee table 2",
    ro: "Masă de cafea 2",
    ru: "Журнальный стол 2",
  },
  {
    vendor_code: "10202-5",
    en: "Dining table 2",
    ro: "Masă de cină 2",
    ru: "Стол обеденный 2",
  },
  {
    vendor_code: "10202-6",
    en: "Kitchen Chair 3",
    ro: "Scaun pentru bucătărie 3",
    ru: "Стул для кухни 3",
  },
  {
    vendor_code: "10202-7",
    en: "Coffee table 3",
    ro: "Masă de cafea 3",
    ru: "Журнальный стол 3",
  },
  {
    vendor_code: "10202-8",
    en: "Glass table Atray 1",
    ro: " Masă de sticlă Atray 1",
    ru: "Стеклянный стол Атрей 1",
  },
  {
    vendor_code: "10202-9",
    en: "Dining table 3",
    ro: "Masă de cină 3",
    ru: "Стол обеденный 3",
  },
  {
    vendor_code: "10202-10",
    en: "Dining table 3",
    ro: "Masă de cină 3",
    ru: "Стол обеденный 3",
  },
  {
    vendor_code: "10202-11",
    en: "Folding garden table 1",
    ro: "Masă pliabilă de grădină 1",
    ru: "Стол складной садовый 1",
  },
  {
    vendor_code: "10203-1",
    en: "Stool 1",
    ro: "Scaun 1",
    ru: "Табурет 1",
  },
  {
    vendor_code: "10203-2",
    en: "Wooden Stool 1",
    ro: "Scaun din lemn 1",
    ru: "Табурет деревянный 1",
  },
  {
    vendor_code: "10203-3",
    en: "Kitchen Stool 1",
    ro: "Scaun de bucătărie 1",
    ru: "Табурет для кухни 1",
  },
  {
    vendor_code: "10203-4",
    en: "Wooden Stool 2",
    ro: "Scaun din lemn 2",
    ru: "Табурет деревянный 2",
  },
  {
    vendor_code: "10203-5",
    en: "Kitchen Stool 2",
    ro: "Scaun de bucătărie 2",
    ru: "Табурет для кухни 2",
  },
  {
    vendor_code: "10301-1",
    en: "Office Chair 1",
    ro: "Scaun de birou 1",
    ru: "Офисное кресло 1",
  },
  {
    vendor_code: "10301-2",
    en: "Executive Chair 1",
    ro: "Scaun executiv 1",
    ru: "Кресло руководителя 1",
  },
  {
    vendor_code: "10301-3",
    en: "Computer Chair 1",
    ro: "Scaun pentru calculator 1",
    ru: "Кресло компьютерное 1",
  },
  {
    vendor_code: "10301-4",
    en: "Gaming Chair 1",
    ro: "Scaun de jocuri 1",
    ru: "Кресло игровое 1",
  },
  {
    vendor_code: "10301-5",
    en: "Executive Chair 2",
    ro: "Scaun executiv 2",
    ru: "Кресло руководителя 2",
  },
  {
    vendor_code: "10301-6",
    en: "Office Chair 1",
    ro: "Scaun de birou 1",
    ru: "Офисное кресло 1",
  },
  {
    vendor_code: "10302-1",
    en: "Writing Desk 1",
    ro: "Birou de scris 1",
    ru: "Стол письменный 1",
  },
  {
    vendor_code: "10302-2",
    en: "Gaming Computer Desk 1",
    ro: "Birou de jocuri 1",
    ru: "Игровой компьютерный стол 1",
  },
  {
    vendor_code: "10302-3",
    en: "Computer Desk 1",
    ro: "Birou pentru calculator 1",
    ru: "Стол компьютерный 1",
  },
  {
    vendor_code: "10302-4",
    en: "Writing Desk 2",
    ro: "Birou de scris 2",
    ru: "Стол письменный 2",
  },
  {
    vendor_code: "10302-5",
    en: "Computer Desk 2",
    ro: "Birou pentru calculator 2",
    ru: "Стол компьютерный 2",
  },
  {
    vendor_code: "10302-6",
    en: "Ritmix Desk 1",
    ro: "Birou Ritmix 1",
    ru: "Стол Ritmix 1",
  },
  {
    vendor_code: "10303-1",
    en: "Office Chair 1",
    ro: "Scaun de birou 1",
    ru: "Офисный стул 1",
  },
  {
    vendor_code: "10303-2",
    en: "Orthopedic Chair 1",
    ro: "Scaun ortopedic 1",
    ru: "Ортопедический стул 1",
  },
  {
    vendor_code: "10303-3",
    en: "Computer Chair 1",
    ro: "Scaun pentru calculator 1",
    ru: "Стул компьютерный 1",
  },
  {
    vendor_code: "10303-4",
    en: "Office Chair 2",
    ro: "Scaun de birou 2",
    ru: "Офисный стул 2",
  },
  {
    vendor_code: "10303-5",
    en: "Orthopedic Chair 2",
    ro: "Scaun ortopedic 2",
    ru: "Ортопедический стул 2",
  },
  {
    vendor_code: "10303-6",
    en: "Orthopedic Chair 3",
    ro: "Scaun ortopedic 3",
    ru: "Ортопедический стул 3",
  },
  {
    vendor_code: "10401-1",
    en: "Sliding Door Wardrobe 1",
    ro: "Dulap cu uși glisante 1",
    ru: "Шкаф купе 1",
  },
  {
    vendor_code: "10401-2",
    en: "Hinged Door Wardrobe 1",
    ro: "Dulap cu uși cu balamale 1",
    ru: "Шкаф распашной 1",
  },
  {
    vendor_code: "10401-3",
    en: "Santori Wardrobe 1",
    ro: "Dulap Santori 1",
    ru: "Шкаф Сантори 1",
  },
  {
    vendor_code: "10401-4",
    en: "Hinged Door Wardrobe 2",
    ro: "Dulap cu uși cu balamale 2",
    ru: "Шкаф распашной 2",
  },
  {
    vendor_code: "10401-5",
    en: "Wall-mounted Wardrobe 1",
    ro: "Dulap montat pe perete 1",
    ru: "Шкаф навесной 1",
  },
  {
    vendor_code: "10402-1",
    en: "Stockholm Dresser 1",
    ro: "Comod Stockholm 1",
    ru: "Комод Стокгольм 1",
  },
  {
    vendor_code: "10402-2",
    en: "Clothing Dresser 1",
    ro: "Comod pentru haine 1",
    ru: "Комод для одежды 1",
  },
  {
    vendor_code: "10402-3",
    en: "Wooden Dresser 1",
    ro: "Comod din lemn 1",
    ru: "Комод деревянный 1",
  },
  {
    vendor_code: "10402-4",
    en: "Wooden Dresser 2",
    ro: "Comod din lemn 2",
    ru: "Комод деревянный 2",
  },
  {
    vendor_code: "10402-5",
    en: "Clothing Dresser 2",
    ro: "Comod pentru haine 2",
    ru: "Комод для одежды 2",
  },
  {
    vendor_code: "10403-1",
    en: "Bedside Table 1",
    ro: "Noptieră 1",
    ru: "Тумба прикроватная 1",
  },
  {
    vendor_code: "10403-2",
    en: "Bedside Table 2",
    ro: "Noptieră 2",
    ru: "Тумба прикроватная 2",
  },
  {
    vendor_code: "10403-3",
    en: "Nightstand with Drawers 1",
    ro: "Noptieră cu sertare 1",
    ru: "Тумба с ящиками 1",
  },
  {
    vendor_code: "10403-4",
    en: "Bedside Table 3",
    ro: "Noptieră 3",
    ru: "Тумба прикроватная 3",
  },
  {
    vendor_code: "10403-5",
    en: "Bedside Table 4",
    ro: "Noptieră 4",
    ru: "Тумба прикроватная 4",
  },
  {
    vendor_code: "10501-1",
    en: "Freestanding Coat Rack 1",
    ro: "Cuier independent 1",
    ru: "Вешалка напольная 1",
  },
  {
    vendor_code: "10501-2",
    en: "Freestanding Coat Rack 2",
    ro: "Cuier independent 2",
    ru: "Вешалка напольная 2",
  },
  {
    vendor_code: "10501-3",
    en: "Freestanding Coat Stand 1",
    ro: "Stativ de haine independent 1",
    ru: "Вешалка-стойка напольная 1",
  },
  {
    vendor_code: "10502-1",
    en: "Shoe Shelf 1",
    ro: "Raft pentru pantofi 1",
    ru: "Этажерка для обуви 1",
  },
  {
    vendor_code: "10502-2",
    en: "Shoe Rack 1",
    ro: "Raft pentru pantofi 1",
    ru: "Полка для обуви 1",
  },
  {
    vendor_code: "10502-3",
    en: "Shoe Shelf 2",
    ro: "Raft pentru pantofi 2",
    ru: "Этажерка для обуви 2",
  },
  {
    vendor_code: "10502-4",
    en: "Metal Shoe Cabinet 1",
    ro: "Dulap metalic pentru pantofi 1",
    ru: "Металлическая обувница 1",
  },
]

const itemsNameArr: ItemsName[] = []

for (let i = 0; i < itemsArr.length; i++) {
  const names = itemsNameBasis.find(
    (el) =>
      el.vendor_code ===
      `${itemsArr[i].category_code}-${itemsArr[i].serial_number}`
  )
  itemsNameArr.push({
    vendor_code: `${itemsArr[i].category_code}-${itemsArr[i].serial_number}-${itemsArr[i].variation}`,
    en: `${names?.en}`,
    ro: `${names?.ro}`,
    ru: `${names?.ru}`,
  })
}

export { itemsNameArr }
